# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: Classification

from __future__ import annotations

from enum import StrEnum


class Classification(StrEnum):
    ClassificationPublic = "public"
    ClassificationPrivate = "private"
