# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: Comment

from typing import Annotated

from pydantic import AwareDatetime, BaseModel, Field, RootModel


class NativeId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="A source's own opaque identifier for one item.\n\nDeliberately unvalidated: a native id is whatever the upstream system says it\nis, colons included. The engine parses a qualified id by splitting on the\n*first* colon precisely so this stays true."
        ),
    ]


class Comment(BaseModel):
    author: Annotated[
        str | None,
        Field(description="Who wrote it, in the source's own spelling of a person."),
    ] = None
    body: Annotated[
        str,
        Field(
            description="What it says, byte for byte as it was written — a trailing newline included."
        ),
    ]
    created_at: Annotated[
        AwareDatetime | None, Field(description="When the source says it was written.")
    ] = None
    id: Annotated[
        NativeId,
        Field(
            description="The comment's own id, exactly as its source issued it.\n\nOpaque, as every [`NativeId`] is, and never qualified: a comment is addressed through\nthe qualified id of the task it is on, so its own id needs no source of its own."
        ),
    ]
    updated_at: Annotated[
        AwareDatetime | None, Field(description="When the source says it last changed.")
    ] = None
    url: Annotated[str | None, Field(description="Where a person can open it.")] = None
