# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: CopyReport

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, Field, RootModel


class CopyAction(StrEnum):
    CopyActionCreated = "created"
    CopyActionUpdated = "updated"
    CopyActionUnchanged = "unchanged"
    CopyActionOrphaned = "orphaned"


class GlobalId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="One item, qualified by the source it came from.\n\nRendered `<source>:<native>` and parsed by splitting on the **first** colon,\nso a native id may contain colons freely."
        ),
    ]


class CopyOutcome(BaseModel):
    action: Annotated[CopyAction, Field(description="Which of the four things happened.")]
    destination: Annotated[
        GlobalId | None,
        Field(
            description="The qualified id it was written to, or `null` for a dry run that would create."
        ),
    ] = None
    source: Annotated[GlobalId, Field(description="The qualified id the item was read from.")]


class CopyReport(BaseModel):
    items: Annotated[
        list[CopyOutcome],
        Field(
            description="One entry per item the copy considered, in the order it considered them."
        ),
    ]
