# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: CopyReport

from typing import Annotated, Literal

from pydantic import BaseModel, Field, RootModel


class GlobalId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="One item, qualified by the source it came from.\n\nRendered `<source>:<native>` and parsed by splitting on the **first** colon,\nso a native id may contain colons freely."
        ),
    ]


class CopyOutcomeCreatedOrWouldCreate(BaseModel):
    source: Annotated[GlobalId, Field(description="The qualified id the item was read from.")]
    action: Literal["created"]
    destination: Annotated[
        GlobalId | None,
        Field(
            description="The id it was created under, or `null` for a dry run that would have created\none — there is no id, because nothing was."
        ),
    ] = None


class CopyOutcomeUpdated(BaseModel):
    source: Annotated[GlobalId, Field(description="The qualified id the item was read from.")]
    action: Literal["updated"]
    destination: Annotated[GlobalId, Field(description="The item that was updated.")]


class CopyOutcomeUnchanged(BaseModel):
    source: Annotated[GlobalId, Field(description="The qualified id the item was read from.")]
    action: Literal["unchanged"]
    destination: Annotated[GlobalId, Field(description="The item that already said it.")]


class CopyOutcomeOrphaned(BaseModel):
    source: Annotated[GlobalId, Field(description="The qualified id the item was read from.")]
    action: Literal["orphaned"]
    destination: Annotated[GlobalId, Field(description="The item that was left alone.")]


class CopyOutcome(
    RootModel[
        CopyOutcomeCreatedOrWouldCreate
        | CopyOutcomeUpdated
        | CopyOutcomeUnchanged
        | CopyOutcomeOrphaned
    ]
):
    root: Annotated[
        CopyOutcomeCreatedOrWouldCreate
        | CopyOutcomeUpdated
        | CopyOutcomeUnchanged
        | CopyOutcomeOrphaned,
        Field(
            description="What happened to one item.\n\n`action` and `destination` are one value rather than two fields side by side: an\nupdated item without a destination id, or an orphan without one, are states this type\nmust not be able to say — the id *is* what those outcomes are about. The one outcome\nthat legitimately has none is a dry run that would create, because nothing was\ncreated and there is no id to report."
        ),
    ]


class CopyReport(BaseModel):
    items: Annotated[
        list[CopyOutcome],
        Field(
            description="One entry per item the copy considered, in the order it considered them."
        ),
    ]
    references_ambiguous: Annotated[
        int | None,
        Field(
            description="How many of [`Self::references_unresolved`] were left alone because the\ncorrespondence was **ambiguous** rather than merely absent. A sub-count, never\nlarger than it.\n\nSplit out because the two mean different things to a reader. A reference with no\ncounterpart is ordinary and expected under the bound above — the design working. An\nambiguous one says the destination holds duplicate records for one work item, or the\nsource reports one location for two records, and re-running the copy will never\nclear it.",
            ge=0,
        ),
    ] = 0
    references_rewritten: Annotated[
        int | None,
        Field(
            description="Reference occurrences the copy rewrote to the destination's own location for the\nrecord they name.\n\nA silent bound is indistinguishable from a bug, so the copy says what it did to the\nreferences the documents it carried hold. This and the two below are totals over the\nwhole invocation rather than figures per document, and all three default to zero, so\na consumer written against the output before they existed is unaffected.\n\n**What these figures do not claim.** The referent set is a document's own project,\nso a reference to a record in a *different* project is never recognised at all and\ncannot appear in [`Self::references_unresolved`] either. These are the references\nthe copy recognised; they are not a census of every reference a document holds.\nNoticing an out-of-scope reference would need exactly the unbounded destination walk\nthis design refuses.",
            ge=0,
        ),
    ] = 0
    references_unresolved: Annotated[
        int | None,
        Field(
            description="Reference occurrences the copy recognised and left byte-for-byte as they were,\nbecause the correspondence could not be established.",
            ge=0,
        ),
    ] = 0
