# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: CopyReport

from typing import Annotated, Literal

from pydantic import BaseModel, Field, RootModel


class GlobalId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="One item, qualified by the source it came from.\n\nRendered `<source>:<native>` and parsed by splitting on the **first** colon,\nso a native id may contain colons freely."
        ),
    ]


class CopyOutcomeCreatedOrWouldCreate(BaseModel):
    source: Annotated[GlobalId, Field(description="The qualified id the item was read from.")]
    action: Literal["created"]
    destination: Annotated[
        GlobalId | None,
        Field(
            description="The id it was created under, or `null` for a dry run that would have created\none — there is no id, because nothing was."
        ),
    ] = None


class CopyOutcomeUpdated(BaseModel):
    source: Annotated[GlobalId, Field(description="The qualified id the item was read from.")]
    action: Literal["updated"]
    destination: Annotated[GlobalId, Field(description="The item that was updated.")]


class CopyOutcomeUnchanged(BaseModel):
    source: Annotated[GlobalId, Field(description="The qualified id the item was read from.")]
    action: Literal["unchanged"]
    destination: Annotated[GlobalId, Field(description="The item that already said it.")]


class CopyOutcomeOrphaned(BaseModel):
    source: Annotated[GlobalId, Field(description="The qualified id the item was read from.")]
    action: Literal["orphaned"]
    destination: Annotated[GlobalId, Field(description="The item that was left alone.")]


class CopyOutcome(
    RootModel[
        CopyOutcomeCreatedOrWouldCreate
        | CopyOutcomeUpdated
        | CopyOutcomeUnchanged
        | CopyOutcomeOrphaned
    ]
):
    root: Annotated[
        CopyOutcomeCreatedOrWouldCreate
        | CopyOutcomeUpdated
        | CopyOutcomeUnchanged
        | CopyOutcomeOrphaned,
        Field(
            description="What happened to one item.\n\n`action` and `destination` are one value rather than two fields side by side: an\nupdated item without a destination id, or an orphan without one, are states this type\nmust not be able to say — the id *is* what those outcomes are about. The one outcome\nthat legitimately has none is a dry run that would create, because nothing was\ncreated and there is no id to report."
        ),
    ]


class CopyReport(BaseModel):
    items: Annotated[
        list[CopyOutcome],
        Field(
            description="One entry per item the copy considered, in the order it considered them."
        ),
    ]
