# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: DeliveryOutcome

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, Field, RootModel


class FailureClass(StrEnum):
    FailureClassRefused = "refused"
    FailureClassTransient = "transient"


class SourceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name a configuration document gives one configured source.",
            pattern="^[a-z0-9][a-z0-9-]*$",
        ),
    ]


class StatusCategory(StrEnum):
    StatusCategoryDraft = "draft"
    StatusCategoryBacklog = "backlog"
    StatusCategoryTodo = "todo"
    StatusCategoryQueued = "queued"
    StatusCategoryInProgress = "in-progress"
    StatusCategoryDone = "done"
    StatusCategoryCancelled = "cancelled"
    StatusCategoryUnknown = "unknown"


class DeliveryOutcomeWritten(BaseModel):
    from_: Annotated[StatusCategory, Field(alias="from", description="The category it read.")]
    outcome: Literal["written"]
    to: Annotated[StatusCategory, Field(description="The category written.")]


class DeliveryOutcomeUnchanged(BaseModel):
    from_: Annotated[StatusCategory, Field(alias="from", description="The category it read.")]
    outcome: Literal["unchanged"]


class DeliveryOutcomeLeft(BaseModel):
    from_: Annotated[StatusCategory, Field(alias="from", description="The category it read.")]
    outcome: Literal["left"]


class Failure(BaseModel):
    class_: Annotated[
        FailureClass,
        Field(
            alias="class",
            description="Whether repeating the request unchanged could change the answer.",
        ),
    ]
    kind: Annotated[
        str,
        Field(
            description="What failed: the causing source error's own `kind` when a source caused it, and\notherwise this product's kebab-case name for the failure, such as `no-such-item`."
        ),
    ]
    message: Annotated[
        str,
        Field(
            description="What the command reported on standard error, without its `onetaskgraph: ` prefix."
        ),
    ]
    retry_after_seconds: Annotated[
        int | None,
        Field(
            description="How many seconds a rate limit asked the caller to wait, or `null` when it named no\nwait.",
            ge=0,
        ),
    ]
    source: Annotated[
        SourceName | None,
        Field(description="The configured source the failure came from, or `null` when none did."),
    ]


class DeliveryOutcomeFailed(BaseModel):
    failure: Annotated[
        Failure,
        Field(
            description="Why, as the failure object itself: the same `class`, `kind`, `source`, `message`\nand `retry_after_seconds` a failure document carries under its own `failure`\nmember — not that whole document nested again."
        ),
    ]
    from_: Annotated[
        StatusCategory | None,
        Field(alias="from", description="The category it read, when it could be read."),
    ] = None
    outcome: Literal["failed"]


class DeliveryOutcome(
    RootModel[
        DeliveryOutcomeWritten
        | DeliveryOutcomeUnchanged
        | DeliveryOutcomeLeft
        | DeliveryOutcomeFailed
    ]
):
    root: Annotated[
        DeliveryOutcomeWritten
        | DeliveryOutcomeUnchanged
        | DeliveryOutcomeLeft
        | DeliveryOutcomeFailed,
        Field(
            description="The four things re-evaluating a delivered task can come to, and the categories each is\nabout.",
            title="DeliveryOutcome",
        ),
    ]
