# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: Document

from typing import Annotated

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, JsonValue, RootModel


class Location1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str


class Location2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str


class Location(RootModel[Location1 | Location2]):
    root: Annotated[
        Location1 | Location2,
        Field(
            description='Where an entity is, in the one form a consumer can act on without knowing the backend.\n\nExternally tagged with exactly two variants, so the JSON is `{"url": "https://…"}` or\n`{"path": "/home/…"}` and a consumer tells them apart by which key is present. A reader\nhanded one of these knows what to *do* with it — open a link, or print a path and read\nthe file out — which is what a bare string could not have said.\n\nIt carries no third case on purpose. `None` on the field is the third case, and it\nmeans the source did not say where the entity is, which is not the same as saying it is\nnowhere.\n\nThis does **not** redefine, replace or derive from the `url` field of [`Task`],\n[`Project`] or [`Document`]: a source that reports a web URL there goes on reporting\nit, and every existing consumer sees exactly what it saw.'
        ),
    ]


class NativeId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="A source's own opaque identifier for one item.\n\nDeliberately unvalidated: a native id is whatever the upstream system says it\nis, colons included. The engine parses a qualified id by splitting on the\n*first* colon precisely so this stays true."
        ),
    ]


class Repository(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="A repository identified by its normalized origin, without a URL scheme or `.git` suffix."
        ),
    ]


class Label(BaseModel):
    color: Annotated[
        str | None,
        Field(description="The source's own colour for the label, when it has one."),
    ] = None
    id: Annotated[NativeId, Field(description="The source's own opaque identifier.")]
    name: Annotated[str, Field(description="What a user filtering across sources actually types.")]


class Document(BaseModel):
    content: Annotated[
        str | None, Field(description="The long-form body, when the source has one.")
    ] = None
    created_at: Annotated[
        AwareDatetime | None, Field(description="When the source says it was created.")
    ] = None
    id: Annotated[NativeId, Field(description="The source's own opaque identifier.")]
    labels: Annotated[list[Label], Field(description="Inline, on the same terms as a [`Task`]'s.")]
    location: Annotated[
        Location | None,
        Field(description="Where it is, when the source says (see [`Location`])."),
    ] = None
    metadata: Annotated[
        dict[str, JsonValue] | None,
        Field(
            description="Caller-defined attributes, preserving their JSON types, with the same reserved\nprefixes [`Task::metadata`] carries."
        ),
    ] = {}
    project: Annotated[
        NativeId | None,
        Field(
            description="The project it lives in; `None` is an orphan document, exactly as it is on a\n[`Task`]."
        ),
    ] = None
    repositories: Annotated[
        list[Repository] | None,
        Field(
            description="Normalized repository origins this document concerns, in source order and without\nrepeats, as a [`Task`]'s.",
            validate_default=True,
        ),
    ] = []
    title: Annotated[str, Field(description="The one-line summary a person recognises it by.")]
    updated_at: Annotated[
        AwareDatetime | None, Field(description="When the source says it last changed.")
    ] = None
    url: Annotated[
        str | None,
        Field(description="Where a person can open it, on the same terms as a [`Task`]'s."),
    ] = None
