# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: EffectiveConfig

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field, RootModel


class CredentialLayer(StrEnum):
    CredentialLayerEnvironment = "environment"
    CredentialLayerSecretsFile = "secrets-file"


class CredentialName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name of an environment variable a credential arrives under.\n\nA newtype rather than a `String` because the domain is real and narrow — what a\nshell could have exported — and a report naming something outside it would be\nreporting a credential that no layer could ever resolve. [`CredentialName::new`] is\nthe only way to make one, so that report cannot be built."
        ),
    ]


class OriginDefault(BaseModel):
    layer: Literal["default"]


class OriginFile(BaseModel):
    layer: Literal["file"]
    path: Annotated[str, Field(description="The document that set it.")]


class OriginEnvironment(BaseModel):
    layer: Literal["environment"]
    variable: Annotated[str, Field(description="The variable that set it.")]


class OriginFlag(BaseModel):
    flag: Annotated[str, Field(description="The flag that set it, as a user typed it.")]
    layer: Literal["flag"]


class Origin(RootModel[OriginDefault | OriginFile | OriginEnvironment | OriginFlag]):
    root: Annotated[
        OriginDefault | OriginFile | OriginEnvironment | OriginFlag,
        Field(
            description="Where one setting's value came from.\n\nThis is what makes precedence provable rather than asserted: `config show`\nrenders it per setting, so a user sees the same answer a test does."
        ),
    ]


class ResolvedCredential(BaseModel):
    resolved_from: Annotated[
        CredentialLayer,
        Field(description="The layer whose value a plugin would receive."),
    ]
    variable: Annotated[CredentialName, Field(description="The variable's name. Never its value.")]


class SecretsReport(BaseModel):
    path: Annotated[
        str | None,
        Field(description="The file that was looked for, whether or not it was there."),
    ] = None
    variables: Annotated[
        list[ResolvedCredential],
        Field(description="Every name the file defines, in order."),
    ]


class SettingPath(RootModel[str]):
    root: Annotated[
        str,
        Field(description="A dotted path to one setting, such as `sources.work.config.root`."),
    ]


class Setting(BaseModel):
    key: Annotated[SettingPath, Field(description="The dotted path of the setting.")]
    origin: Annotated[Origin, Field(description="Where the value came from.")]
    # A setting is arbitrary JSON by the emitted wire contract.
    value: Annotated[Any, Field(description="Its value.")]


class EffectiveConfig(BaseModel):
    secrets: Annotated[
        SecretsReport,
        Field(
            description="What the credentials file supplied, by name, and which layer answers for each.\n\nBeside the settings because it is the same question — where does this value\ncome from — asked of the one kind of value that may never be printed. So the\nname and the layer are reported and the value never is."
        ),
    ]
    settings: Annotated[list[Setting], Field(description="Every setting, in key order.")]
