# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: FailureDocument

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, Field, RootModel


class FailureClass(StrEnum):
    FailureClassRefused = "refused"
    FailureClassTransient = "transient"


class SourceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name a configuration document gives one configured source.",
            pattern="^[a-z0-9][a-z0-9-]*$",
        ),
    ]


class Failure(BaseModel):
    class_: Annotated[
        FailureClass,
        Field(
            alias="class",
            description="Whether repeating the request unchanged could change the answer.",
        ),
    ]
    kind: Annotated[
        str,
        Field(
            description="What failed: the causing source error's own `kind` when a source caused it, and\notherwise this product's kebab-case name for the failure, such as `no-such-item`."
        ),
    ]
    message: Annotated[
        str,
        Field(
            description="What the command reported on standard error, without its `onetaskgraph: ` prefix."
        ),
    ]
    retry_after_seconds: Annotated[
        int | None,
        Field(
            description="How many seconds a rate limit asked the caller to wait, or `null` when it named no\nwait.",
            ge=0,
        ),
    ]
    source: Annotated[
        SourceName | None,
        Field(description="The configured source the failure came from, or `null` when none did."),
    ]


class FailureDocument(BaseModel):
    failure: Annotated[Failure, Field(description="Why the command failed.")]
