# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: FieldsReport

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, Field, RootModel


class BoardField(StrEnum):
    BoardFieldStatus = "Status"
    BoardFieldPriority = "Priority"


class ColumnName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name of a `Status` single-select option on the board.\n\nValidated on the way in rather than checked later, so a blank option name — which\nnothing on a board can be — is a state this type cannot hold.",
            min_length=1,
        ),
    ]


class FieldOutcome(StrEnum):
    FieldOutcomePlanned = "planned"
    FieldOutcomeUnchanged = "unchanged"
    FieldOutcomeApplied = "applied"
    FieldOutcomeCreated = "created"


class ItemKind(StrEnum):
    ItemKindTask = "task"
    ItemKindProject = "project"


class KindMissing(BaseModel):
    kind: Annotated[ItemKind, Field(description="The kind these names are configured for.")]
    missing: Annotated[
        list[str],
        Field(
            description="The names that kind maps a category to and the field lacked, in category order."
        ),
    ]


class NonTextFieldType(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The type of a board field that is not a text field, as GitHub names it — its `dataType`, or\nits GraphQL type when it has none — which is what a projected field's conflict reports.\n\nNever empty, never beginning with whitespace, and never `TEXT`: a text field of that name is\nno conflict.",
            pattern="^(?:[^T\\s]|T(?:[^E]|$)|TE(?:[^X]|$)|TEX(?:[^T]|$)|TEXT[\\s\\S])",
        ),
    ]


class SourceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name a configuration document gives one configured source.",
            pattern="^[a-z0-9][a-z0-9-]*$",
        ),
    ]


class StatusOptionColor(StrEnum):
    StatusOptionColorGray = "GRAY"
    StatusOptionColorBlue = "BLUE"
    StatusOptionColorGreen = "GREEN"
    StatusOptionColorYellow = "YELLOW"
    StatusOptionColorPurple = "PURPLE"
    StatusOptionColorRed = "RED"
    StatusOptionColorOrange = "ORANGE"
    StatusOptionColorPink = "PINK"


class StatusOptionId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="A GitHub single-select option's opaque GraphQL node identifier.",
            min_length=1,
        ),
    ]


class MetadataFieldReport(BaseModel):
    conflict: Annotated[
        NonTextFieldType | None,
        Field(
            description="The type of a field of that name that is not a text field, which the setup leaves as\nit is; absent — and left out of the JSON — when there is none."
        ),
    ] = None
    exists: Annotated[
        bool,
        Field(description="Whether the board had a text field of that name before the operation."),
    ]
    field: Annotated[str, Field(description="The board field's name.")]
    key: Annotated[str, Field(description="The metadata key the value is read from.")]
    outcome: Annotated[
        FieldOutcome,
        Field(
            description="What the requested operation did: `planned`; `created` for a field that was not\nthere; `unchanged` for one that was, and for a conflict, which is never changed."
        ),
    ]
    path: Annotated[
        list[str],
        Field(
            description="The object keys walked inside that key's value; empty for the key's own value."
        ),
    ]


class StatusOption(BaseModel):
    color: Annotated[StatusOptionColor, Field(description="GitHub's single-select color token.")]
    description: Annotated[
        str, Field(description="The option description, including an empty one.")
    ]
    id: Annotated[StatusOptionId, Field(description="GitHub's stable id.")]
    name: Annotated[ColumnName, Field(description="The visible option name.")]


class FieldReport(BaseModel):
    existing: Annotated[
        list[StatusOption],
        Field(
            description="The field's complete option list observed before any mutation; empty when the field\nwas not there."
        ),
    ]
    exists: Annotated[
        bool, Field(description="Whether the board had the field before the operation.")
    ]
    field: Annotated[BoardField, Field(description="Which field.")]
    kinds: Annotated[
        list[KindMissing],
        Field(
            description="For the `Status` field, which item kind each missing name is configured for: one\nentry per kind `status_mapping` names a missing option for, task before project, each\nlisting that kind's missing names in category order. A name both kinds use is in\nboth. Empty — and left out of the JSON — when nothing is missing, and always for\n`Priority`, which only a task holds.",
            validate_default=True,
        ),
    ] = []
    missing: Annotated[
        list[str],
        Field(
            description="Configured option names the field lacked before the operation — every one of them,\nin the order a new field lists them, when the field was not there at all."
        ),
    ]
    outcome: Annotated[FieldOutcome, Field(description="What the requested operation did.")]


class FieldsReport(BaseModel):
    fields: Annotated[
        list[FieldReport],
        Field(
            description="`Status`, always, and `Priority` when the source sets `priority_mapping`."
        ),
    ]
    metadata_fields: Annotated[
        list[MetadataFieldReport],
        Field(
            description="Each board text field the source's `metadata_fields` projects a value onto, in\nconfigured order. Empty — and left out of the JSON — when it projects none.",
            validate_default=True,
        ),
    ] = []
    source: Annotated[SourceName, Field(description="The configured source name.")]
