# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: FieldsReport

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, Field, RootModel


class BoardField(StrEnum):
    BoardFieldStatus = "Status"
    BoardFieldPriority = "Priority"


class ColumnName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name of a `Status` single-select option on the board.\n\nValidated on the way in rather than checked later, so a blank option name — which\nnothing on a board can be — is a state this type cannot hold.",
            min_length=1,
        ),
    ]


class FieldOutcome(StrEnum):
    FieldOutcomePlanned = "planned"
    FieldOutcomeUnchanged = "unchanged"
    FieldOutcomeApplied = "applied"
    FieldOutcomeCreated = "created"


class SourceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name a configuration document gives one configured source.",
            pattern="^[a-z0-9][a-z0-9-]*$",
        ),
    ]


class StatusOptionColor(StrEnum):
    StatusOptionColorGray = "GRAY"
    StatusOptionColorBlue = "BLUE"
    StatusOptionColorGreen = "GREEN"
    StatusOptionColorYellow = "YELLOW"
    StatusOptionColorPurple = "PURPLE"
    StatusOptionColorRed = "RED"
    StatusOptionColorOrange = "ORANGE"
    StatusOptionColorPink = "PINK"


class StatusOptionId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="A GitHub single-select option's opaque GraphQL node identifier.",
            min_length=1,
        ),
    ]


class StatusOption(BaseModel):
    color: Annotated[StatusOptionColor, Field(description="GitHub's single-select color token.")]
    description: Annotated[
        str, Field(description="The option description, including an empty one.")
    ]
    id: Annotated[StatusOptionId, Field(description="GitHub's stable id.")]
    name: Annotated[ColumnName, Field(description="The visible option name.")]


class FieldReport(BaseModel):
    existing: Annotated[
        list[StatusOption],
        Field(
            description="The field's complete option list observed before any mutation; empty when the field\nwas not there."
        ),
    ]
    exists: Annotated[
        bool, Field(description="Whether the board had the field before the operation.")
    ]
    field: Annotated[BoardField, Field(description="Which field.")]
    missing: Annotated[
        list[str],
        Field(
            description="Configured option names the field lacked before the operation — every one of them,\nin the order a new field lists them, when the field was not there at all."
        ),
    ]
    outcome: Annotated[FieldOutcome, Field(description="What the requested operation did.")]


class FieldsReport(BaseModel):
    fields: Annotated[
        list[FieldReport],
        Field(
            description="`Status`, always, and `Priority` when the source sets `priority_mapping`."
        ),
    ]
    source: Annotated[SourceName, Field(description="The configured source name.")]
