# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: ItemType

from __future__ import annotations

from enum import StrEnum


class ItemType(StrEnum):
    ItemTypeString = "string"
    ItemTypeObject = "object"
