# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: LinearConfig

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class LinearProjectId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The id of one Linear project, which a scoped source holds alone.",
            min_length=1,
        ),
    ]


class LinearTeam(RootModel[str]):
    root: Annotated[str, Field(description="A Linear team's key or id.", min_length=1)]


class StatusCategory(StrEnum):
    StatusCategoryDraft = "draft"
    StatusCategoryBacklog = "backlog"
    StatusCategoryTodo = "todo"
    StatusCategoryQueued = "queued"
    StatusCategoryInProgress = "in-progress"
    StatusCategoryDone = "done"
    StatusCategoryCancelled = "cancelled"
    StatusCategoryUnknown = "unknown"


class StatusName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="One status name a source's backend holds, matched ignoring case. Never blank.",
            min_length=1,
            pattern="\\S",
        ),
    ]


class StatusNames1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    task: StatusName


class StatusNames2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    project: StatusName


class StatusNames3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    project: StatusName
    task: StatusName


class StatusNames(RootModel[StatusName | StatusNames1 | StatusNames2 | StatusNames3]):
    root: Annotated[
        StatusName | StatusNames1 | StatusNames2 | StatusNames3,
        Field(
            description="What one category of a status_mapping names: one name for every item kind, or an object naming it for a task, for a project, or for each. A kind the object leaves out leaves the category unmapped for that kind."
        ),
    ]


class StatusMapping(RootModel[dict[StatusCategory, StatusNames | None]]):
    root: Annotated[
        dict[StatusCategory, StatusNames | None],
        Field(
            description="Which name each status category is, for each item kind. Keyed by status category; each value is one name for every kind, null to disable the category for every kind, or an object naming it for a task, a project or each."
        ),
    ]


class LinearConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    api_key_env: Annotated[str, Field(description="Environment variable resolved by the host.")] = (
        "LINEAR_API_KEY"
    )
    endpoint: Annotated[
        str,
        Field(description="GraphQL endpoint override, primarily for fixture servers."),
    ] = "https://api.linear.app/graphql"
    project: Annotated[
        LinearProjectId | None,
        Field(
            description="The id of one Linear project of the configured team, scoping this source to it.\n\nWhen set, every task read is narrowed to that project's issues, project and document\nreads return only that project and its documents, a task or a document written with\nno project is placed in it, and one naming another project is refused. Absent, the\nsource reads and writes team-wide."
        ),
    ] = None
    status_mapping: Annotated[
        StatusMapping,
        Field(
            description="Which workflow state of the configured team a task's status category is, and which of\nthe workspace's project statuses a project's is — the shared `status_mapping` grammar.\n\nLinear has no built-in names, so this is the whole of what a status is written as and\nread by: a category is written as exactly the name its kind maps it to, and a status\nwrite it gives no name for is refused before any mutation, naming the key to set; an\nitem at a name its kind maps reads as that category under the name, and every other\nname reads as `unknown`. A source without it reads every item as `unknown` and refuses\nevery status write. Two categories mapped to one name of one kind are refused when this\nconfiguration is read.",
            validate_default=True,
        ),
    ] = StatusMapping({})
    team: Annotated[
        LinearTeam | None,
        Field(description="Linear team key/id used to narrow reads and required for item writes."),
    ] = None
