# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: Location

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Location1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str


class Location2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str


class Location(RootModel[Location1 | Location2]):
    root: Annotated[
        Location1 | Location2,
        Field(
            description='Where an entity is, in the one form a consumer can act on without knowing the backend.\n\nExternally tagged with exactly two variants, so the JSON is `{"url": "https://…"}` or\n`{"path": "/home/…"}` and a consumer tells them apart by which key is present. A reader\nhanded one of these knows what to *do* with it — open a link, or print a path and read\nthe file out — which is what a bare string could not have said.\n\nIt carries no third case on purpose. `None` on the field is the third case, and it\nmeans the source did not say where the entity is, which is not the same as saying it is\nnowhere.\n\nThis does **not** redefine, replace or derive from the `url` field of [`Task`],\n[`Project`] or [`Document`]: a source that reports a web URL there goes on reporting\nit, and every existing consumer sees exactly what it saw.',
            title="Location",
        ),
    ]
