# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: MetadataSet

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class GlobalId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="One item, qualified by the source it came from.\n\nRendered `<source>:<native>` and parsed by splitting on the **first** colon,\nso a native id may contain colons freely."
        ),
    ]


class Location1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str


class Location2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str


class Location(RootModel[Location1 | Location2]):
    root: Annotated[
        Location1 | Location2,
        Field(
            description='Where an entity is, in the one form a consumer can act on without knowing the backend.\n\nExternally tagged with exactly two variants, so the JSON is `{"url": "https://…"}` or\n`{"path": "/home/…"}` and a consumer tells them apart by which key is present. A reader\nhanded one of these knows what to *do* with it — open a link, or print a path and read\nthe file out — which is what a bare string could not have said.\n\nIt carries no third case on purpose. `None` on the field is the third case, and it\nmeans the source did not say where the entity is, which is not the same as saying it is\nnowhere.\n\nThis does **not** redefine, replace or derive from the `url` field of [`Task`],\n[`Project`] or [`Document`]: a source that reports a web URL there goes on reporting\nit, and every existing consumer sees exactly what it saw.'
        ),
    ]


class MetadataKey(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="One caller-owned metadata key: `<namespace>.<name>`, at least two non-empty segments\nseparated by dots, whose first segment is not [`MetadataKey::RESERVED_NAMESPACE`].\n\nValidated wherever one is built, deserialized included, so a plugin handed one never has\nto ask whether it names a key this product owns."
        ),
    ]


class MetadataSet(BaseModel):
    id: Annotated[GlobalId, Field(description="The record whose metadata key was set.")]
    key: Annotated[MetadataKey, Field(description="The key that was set.")]
    location: Annotated[
        Location | None,
        Field(
            description="Where the source reports the record to be, left out when it does not say."
        ),
    ] = None
    value: Annotated[
        Any,
        Field(
            description="The value the source holds under `key` as it reads the record back after the write —\nwhich is not always the value it was handed."
        ),
    ]
