# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: NativeId

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel


class NativeId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="A source's own opaque identifier for one item.\n\nDeliberately unvalidated: a native id is whatever the upstream system says it\nis, colons included. The engine parses a qualified id by splitting on the\n*first* colon precisely so this stays true.",
            title="NativeId",
        ),
    ]
