# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: Priority

from __future__ import annotations

from enum import StrEnum


class Priority(StrEnum):
    PriorityNone = "none"
    PriorityUrgent = "urgent"
    PriorityHigh = "high"
    PriorityMedium = "medium"
    PriorityLow = "low"
