# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: ProjectGraph

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, Field, RootModel


class GlobalId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="One item, qualified by the source it came from.\n\nRendered `<source>:<native>` and parsed by splitting on the **first** colon,\nso a native id may contain colons freely."
        ),
    ]


class GraphDirection(StrEnum):
    GraphDirectionTd = "td"
    GraphDirectionLr = "lr"


class GraphEdge(BaseModel):
    from_: Annotated[
        GlobalId,
        Field(
            alias="from",
            description="The prerequisite: the task that has to finish first.",
        ),
    ]
    to: Annotated[GlobalId, Field(description="The dependent: the project task that waits on it.")]


class GraphNode(BaseModel):
    external: Annotated[
        bool,
        Field(
            description="Whether the task is outside the project: `true` exactly for the `x<k>` nodes."
        ),
    ]
    group: Annotated[
        str | None,
        Field(
            description="The task's group under `group_by`, or `null` — for a task with none, for every\nexternal task, and for every task when no key was given."
        ),
    ] = None
    id: Annotated[GlobalId, Field(description="The task's qualified id.")]
    key: Annotated[
        str,
        Field(
            description="The Mermaid form's node id: `n<k>` for the project's own tasks and `x<k>` for a task\noutside it, each counted from 1."
        ),
    ]
    title: Annotated[
        str,
        Field(
            description="The task's title, exactly as its source reports it — unescaped and unaltered."
        ),
    ]


class ProjectGraph(BaseModel):
    direction: Annotated[
        GraphDirection,
        Field(description="The direction the graph is laid out in — `auto` already resolved."),
    ]
    edges: Annotated[
        list[GraphEdge],
        Field(
            description="Every dependency, ordered by its prerequisite's position and then its dependent's."
        ),
    ]
    group_by: Annotated[
        str | None,
        Field(description="The `--group-by` key, or `null` when none was given."),
    ] = None
    nodes: Annotated[
        list[GraphNode],
        Field(
            description="Every task of the project in topological order, then every task outside it that one\nof them depends on, ordered by title and then qualified id."
        ),
    ]
    project: Annotated[GlobalId, Field(description="The project whose tasks these are.")]
    schema_version: Annotated[
        int, Field(description="The version of this document's shape; `1`.", ge=0)
    ]
