# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: PublicWriteInput

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class RepositoryVisibility(StrEnum):
    RepositoryVisibilityPublic = "public"
    RepositoryVisibilityPrivate = "private"
    RepositoryVisibilityUnknown = "unknown"


class PublicWriteInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    destination: Annotated[RepositoryVisibility, Field(description="Where it is going.")]
    metadata: Annotated[
        list[str],
        Field(description="Titles, labels, metadata and every other short field."),
    ] = []
    paths: Annotated[list[str], Field(description="Paths it names or writes.")] = []
    scope: Annotated[
        list[str] | None,
        Field(
            description="Which repositories' private terms the check derives, as the caller scoped it."
        ),
    ] = None
    text: Annotated[list[str], Field(description="Prose and file contents.")] = []
