# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: QueryPlan

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, Field, RootModel


class Predicate(StrEnum):
    label = "label"
    status = "status"
    search_title = "search-title"
    search_content = "search-content"
    project = "project"
    reverse_dependencies = "reverse-dependencies"


class SourceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name a configuration document gives one configured source.",
            pattern="^[a-z0-9][a-z0-9-]*$",
        ),
    ]


class SourcePlan(BaseModel):
    applied_locally: Annotated[
        list[Predicate],
        Field(description="Predicates the engine applied in memory over a wider result set."),
    ]
    emulated: Annotated[
        list[Predicate],
        Field(description="Predicates the engine answered by a bounded scan of the source."),
    ]
    kind: Annotated[str, Field(description="The plugin kind behind it.")]
    pages_fetched: Annotated[
        int,
        Field(
            description="How many pages the engine pulled from this source to answer.",
            ge=0,
        ),
    ]
    pushed_down: Annotated[
        list[Predicate],
        Field(
            description="Predicates the source applied itself.\n\nThe four predicate vectors below partition one set of outcomes, and nothing in\nthe type says so: a `Predicate` could appear in two of them at once, or in none.\nOne `Vec<(Predicate, Outcome)>` — or a map keyed by predicate — would make that\nunrepresentable. See the directive below for why it stays as it is."
        ),
    ]
    source: Annotated[SourceName, Field(description="The configured source this describes.")]
    unavailable: Annotated[
        list[Predicate],
        Field(
            description="Predicates neither side could answer, so the result is unconstrained.\n\nNever [`Predicate::ReverseDependencies`]: `DependencySupport` has no\nunsupported variant, so a reverse-dependency read is answered natively or\nemulated by the engine's bounded scan, never abandoned. The type cannot say\nso — see the directive below."
        ),
    ]


class QueryPlan(BaseModel):
    per_source: Annotated[
        list[SourcePlan], Field(description="One entry per source the query reached.")
    ]
