# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: QueryResponseOfSearchHit

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import AwareDatetime, BaseModel, Field, JsonValue, RootModel


class GlobalId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="One item, qualified by the source it came from.\n\nRendered `<source>:<native>` and parsed by splitting on the **first** colon,\nso a native id may contain colons freely."
        ),
    ]


class NativeId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="A source's own opaque identifier for one item.\n\nDeliberately unvalidated: a native id is whatever the upstream system says it\nis, colons included. The engine parses a qualified id by splitting on the\n*first* colon precisely so this stays true."
        ),
    ]


class PageToken(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The engine's own resume token: one plugin cursor per source stream, opaque to the\ncaller exactly as a plugin's cursor is opaque to the engine.\n\nRendered as lower-case hex, which is not obfuscation — the inside is not a secret —\nbut the one property a token a person copies off a terminal has to have: it survives\na shell. The document underneath holds a plugin's own cursor, and a cursor may hold\nanything at all, so a token spelled as the raw JSON would carry quotes, braces and\nspaces straight into the next command line. Hex has no character a shell reads.\n\n# What a token is and is not checked for\n\nBoth ways in go through [`parse`](Self::parse) — including deserialising one — and\nwhat that establishes is **structural**: the string is hex, the bytes are this\nengine's own resume document, and every state in it is well formed. It does not, and\ncannot, establish that this engine is the one that wrote it. A token is not a\ncredential and carries nothing secret; forging one buys a caller nothing they could\nnot have asked for outright, since every cursor inside is handed straight back to the\nsource that issued it and is validated there.\n\nWhat a forged token *could* do is name a stream this configuration has no source for,\nor resume further into a page than the engine ever pages. Both are refused where the\ntoken meets the query it is resuming, by\n[`Engine`](crate::Engine) — see `EngineError::Token` — because only the engine knows\nwhich sources are configured and what page ceiling each declares."
        ),
    ]


class Predicate(StrEnum):
    PredicateLabel = "label"
    PredicateStatus = "status"
    PredicateSearchTitle = "search-title"
    PredicateSearchContent = "search-content"
    PredicateProject = "project"
    PredicateReverseDependencies = "reverse-dependencies"


class Repository(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="A repository identified by its normalized origin, without a URL scheme or `.git` suffix."
        ),
    ]


class SourceErrorConfig(BaseModel):
    kind: Literal["config"]
    message: Annotated[str, Field(description="What is wrong, in a form a user can act on.")]


class SourceErrorAuth(BaseModel):
    kind: Literal["auth"]
    message: Annotated[str, Field(description="What failed. Never contains the credential itself.")]


class SourceErrorRefused(BaseModel):
    kind: Literal["refused"]
    message: Annotated[str, Field(description="The source's own reason.")]


class SourceErrorRateLimited(BaseModel):
    kind: Literal["rate-limited"]
    retry_after_seconds: Annotated[
        int | None,
        Field(description="How long the source asked us to wait, when it said.", ge=0),
    ] = None


class SourceErrorUnavailable(BaseModel):
    kind: Literal["unavailable"]
    message: Annotated[str, Field(description="What went wrong reaching it.")]


class SourceErrorMalformed(BaseModel):
    kind: Literal["malformed"]
    message: Annotated[str, Field(description="What could not be represented.")]


class SourceError(
    RootModel[
        SourceErrorConfig
        | SourceErrorAuth
        | SourceErrorRefused
        | SourceErrorRateLimited
        | SourceErrorUnavailable
        | SourceErrorMalformed
    ]
):
    root: Annotated[
        SourceErrorConfig
        | SourceErrorAuth
        | SourceErrorRefused
        | SourceErrorRateLimited
        | SourceErrorUnavailable
        | SourceErrorMalformed,
        Field(
            description="Why a source could not answer.\n\nEvery variant carries owned data only, so an error survives the JSON-over-stdio\nboundary a subprocess-hosted plugin crosses without losing anything."
        ),
    ]


class SourceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name a configuration document gives one configured source.",
            pattern="^[a-z0-9][a-z0-9-]*$",
        ),
    ]


class SourcePlan(BaseModel):
    applied_locally: Annotated[
        list[Predicate],
        Field(description="Predicates the engine applied in memory over a wider result set."),
    ]
    emulated: Annotated[
        list[Predicate],
        Field(description="Predicates the engine answered by a bounded scan of the source."),
    ]
    kind: Annotated[str, Field(description="The plugin kind behind it.")]
    pages_fetched: Annotated[
        int,
        Field(
            description="How many pages the engine pulled from this source to answer.",
            ge=0,
        ),
    ]
    pushed_down: Annotated[
        list[Predicate],
        Field(
            description="Predicates the source applied itself.\n\nThe four predicate vectors below partition one set of outcomes, and nothing in\nthe type says so: a `Predicate` could appear in two of them at once, or in none.\nOne `Vec<(Predicate, Outcome)>` — or a map keyed by predicate — would make that\nunrepresentable. See the directive below for why it stays as it is."
        ),
    ]
    source: Annotated[SourceName, Field(description="The configured source this describes.")]
    unavailable: Annotated[
        list[Predicate],
        Field(
            description="Predicates neither side could answer, so the result is unconstrained.\n\nNever [`Predicate::ReverseDependencies`]: `DependencySupport` has no\nunsupported variant, so a reverse-dependency read is answered natively or\nemulated by the engine's bounded scan, never abandoned. The type cannot say\nso — see the directive below."
        ),
    ]


class StatusCategory(StrEnum):
    StatusCategoryDraft = "draft"
    StatusCategoryBacklog = "backlog"
    StatusCategoryTodo = "todo"
    StatusCategoryInProgress = "in-progress"
    StatusCategoryDone = "done"
    StatusCategoryCancelled = "cancelled"
    StatusCategoryUnknown = "unknown"


class Label(BaseModel):
    color: Annotated[
        str | None,
        Field(description="The source's own colour for the label, when it has one."),
    ] = None
    id: Annotated[NativeId, Field(description="The source's own opaque identifier.")]
    name: Annotated[str, Field(description="What a user filtering across sources actually types.")]


class QueryPlan(BaseModel):
    per_source: Annotated[
        list[SourcePlan], Field(description="One entry per source the query reached.")
    ]


class SourceFailure(BaseModel):
    error: Annotated[SourceError, Field(description="Why.")]
    source: Annotated[SourceName, Field(description="The source that failed.")]


class Status(BaseModel):
    category: Annotated[
        StatusCategory,
        Field(description="The normalised value filters compare against."),
    ]
    name: Annotated[str, Field(description="The source's own label for this status.")]


class Task(BaseModel):
    content: Annotated[
        str | None, Field(description="The long-form body, when the source has one.")
    ] = None
    created_at: Annotated[
        AwareDatetime | None,
        Field(description="When the source says the task was created."),
    ] = None
    id: Annotated[NativeId, Field(description="The source's own opaque identifier.")]
    labels: Annotated[
        list[Label],
        Field(
            description="Inline rather than by id: a source returning a task already knows them."
        ),
    ]
    metadata: Annotated[
        dict[str, JsonValue] | None,
        Field(
            description="Caller-defined attributes, preserving their JSON types.\n\nKeys are free-form, with two reserved prefixes: `onetaskgraph.` belongs to this\nproduct — [`Repository::METADATA_KEY`] and [`DependencyEdge::RECORDED_KEY`] are\nthe two it defines — and `onepipeline.` belongs to that consumer. Every other key\nis the caller's, and a source returns it exactly as it holds it."
        ),
    ] = {}
    project: Annotated[
        NativeId | None,
        Field(description="`None` is a first-class case — an orphan task — not an edge case."),
    ] = None
    repositories: Annotated[
        list[Repository] | None,
        Field(
            description="Normalized repository origins this task concerns, in source order and without\nrepeats.",
            validate_default=True,
        ),
    ] = []
    status: Annotated[Status, Field(description="The source's status, normalised and preserved.")]
    title: Annotated[str, Field(description="The one-line summary a user recognises the task by.")]
    updated_at: Annotated[
        AwareDatetime | None,
        Field(description="When the source says the task last changed."),
    ] = None
    url: Annotated[str | None, Field(description="Where a human can open this task.")] = None


class QualifiedTask(BaseModel):
    id: Annotated[
        GlobalId,
        Field(description="`<source>:<native>`, the form a user types back at the command line."),
    ]
    item: Annotated[Task, Field(description="The item as its source reported it, unchanged.")]


class Project(BaseModel):
    content: Annotated[
        str | None, Field(description="The long-form body, when the source has one.")
    ] = None
    created_at: Annotated[
        AwareDatetime | None,
        Field(description="When the source says the project was created."),
    ] = None
    id: Annotated[NativeId, Field(description="The source's own opaque identifier.")]
    labels: Annotated[
        list[Label],
        Field(description="Inline rather than by id, for the same reason as on [`Task`]."),
    ]
    metadata: Annotated[
        dict[str, JsonValue] | None,
        Field(
            description="Caller-defined attributes, preserving their JSON types, on the same terms as\n[`Task::metadata`]."
        ),
    ] = {}
    repositories: Annotated[
        list[Repository] | None,
        Field(
            description="Normalized repository origins this project concerns, in source order and without\nrepeats.",
            validate_default=True,
        ),
    ] = []
    status: Annotated[Status, Field(description="The source's status, normalised and preserved.")]
    title: Annotated[
        str, Field(description="The one-line summary a user recognises the project by.")
    ]
    updated_at: Annotated[
        AwareDatetime | None,
        Field(description="When the source says the project last changed."),
    ] = None
    url: Annotated[str | None, Field(description="Where a human can open this project.")] = None


class SearchHitTask(BaseModel):
    id: Annotated[
        GlobalId,
        Field(description="`<source>:<native>`, the form a user types back at the command line."),
    ]
    item: Annotated[Task, Field(description="The item as its source reported it, unchanged.")]
    kind: Literal["task"]


class SearchHitProject(BaseModel):
    id: Annotated[
        GlobalId,
        Field(description="`<source>:<native>`, the form a user types back at the command line."),
    ]
    item: Annotated[Project, Field(description="The item as its source reported it, unchanged.")]
    kind: Literal["project"]


class SearchHit(RootModel[SearchHitTask | SearchHitProject]):
    root: Annotated[
        SearchHitTask | SearchHitProject,
        Field(description="One hit of a search that may cross entities."),
    ]


class QualifiedProject(BaseModel):
    id: Annotated[
        GlobalId,
        Field(description="`<source>:<native>`, the form a user types back at the command line."),
    ]
    item: Annotated[Project, Field(description="The item as its source reported it, unchanged.")]


class QueryResponse(BaseModel):
    errors: Annotated[
        list[SourceFailure],
        Field(description="Sources that failed. One failure never fails the whole query."),
    ]
    items: Annotated[
        list[SearchHit],
        Field(description="This page's items, already qualified and merged across sources."),
    ]
    next: Annotated[
        PageToken | None,
        Field(description="Where to resume, or `None` when every source is exhausted."),
    ] = None
    plan: Annotated[
        QueryPlan,
        Field(description="What each source was asked to do, and what the engine did instead."),
    ]
