# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: Regenerated

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field, RootModel


class GlobalId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="One item, qualified by the source it came from.\n\nRendered `<source>:<native>` and parsed by splitting on the **first** colon,\nso a native id may contain colons freely."
        ),
    ]


class Regenerated(BaseModel):
    body: Annotated[str, Field(description="The rendered content.")]
    body_digest: Annotated[
        str,
        Field(description="The SHA-256 of the rendered content: what its provenance now records."),
    ]
    changed: Annotated[
        bool,
        Field(
            description="Whether its content, its provenance or its stored answers differ from what it held —\nwhat a write changed, or for a dry run what one would change."
        ),
    ]
    digest: Annotated[str, Field(description="The chain digest it rendered with.")]
    id: Annotated[GlobalId, Field(description="The item regenerated.")]
