# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: RenderedTemplate

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field, JsonValue


class RenderedTemplate(BaseModel):
    answers: Annotated[
        dict[str, JsonValue],
        Field(
            description="Every declared variable and the value it rendered with — an answer, a default, or\n`null` for an optional variable given neither."
        ),
    ]
    body: Annotated[str, Field(description="The rendered text.")]
    digest: Annotated[
        str,
        Field(
            description="The digest of every file of the chain these answers render, in first-load order:\n`sha256:` and 64 lowercase hex digits. That is the order the render first read each\nfile, a template an expression named included, then any file of the chain it did not\nread."
        ),
    ]
