# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: RepositoryVisibility

from __future__ import annotations

from enum import StrEnum


class RepositoryVisibility(StrEnum):
    RepositoryVisibilityPublic = "public"
    RepositoryVisibilityPrivate = "private"
    RepositoryVisibilityUnknown = "unknown"
