# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: SourceFailure

from typing import Annotated, Literal

from pydantic import BaseModel, Field, RootModel


class SourceErrorConfig(BaseModel):
    kind: Literal["config"]
    message: Annotated[str, Field(description="What is wrong, in a form a user can act on.")]


class SourceErrorAuth(BaseModel):
    kind: Literal["auth"]
    message: Annotated[str, Field(description="What failed. Never contains the credential itself.")]


class SourceErrorRefused(BaseModel):
    kind: Literal["refused"]
    message: Annotated[str, Field(description="The source's own reason.")]


class SourceErrorRateLimited(BaseModel):
    kind: Literal["rate-limited"]
    message: Annotated[
        str | None,
        Field(
            description="What the source can add about *which* limit refused it and what it was doing.\n\nAbsent means the source had nothing to add beyond the kind, which is what\nevery source said before this member existed; it is omitted from the wire\nentirely when absent, so a reader written against the shape without it sees\nexactly the shape it was written for. Never contains a credential."
        ),
    ] = None
    retry_after_seconds: Annotated[
        int | None,
        Field(description="How long the source asked us to wait, when it said.", ge=0),
    ] = None


class SourceErrorUnavailable(BaseModel):
    kind: Literal["unavailable"]
    message: Annotated[str, Field(description="What went wrong reaching it.")]


class SourceErrorMalformed(BaseModel):
    kind: Literal["malformed"]
    message: Annotated[str, Field(description="What could not be represented.")]


class SourceError(
    RootModel[
        SourceErrorConfig
        | SourceErrorAuth
        | SourceErrorRefused
        | SourceErrorRateLimited
        | SourceErrorUnavailable
        | SourceErrorMalformed
    ]
):
    root: Annotated[
        SourceErrorConfig
        | SourceErrorAuth
        | SourceErrorRefused
        | SourceErrorRateLimited
        | SourceErrorUnavailable
        | SourceErrorMalformed,
        Field(
            description="Why a source could not answer.\n\nEvery variant carries owned data only, so an error survives the JSON-over-stdio\nboundary a subprocess-hosted plugin crosses without losing anything."
        ),
    ]


class SourceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name a configuration document gives one configured source.",
            pattern="^[a-z0-9][a-z0-9-]*$",
        ),
    ]


class SourceFailure(BaseModel):
    error: Annotated[SourceError, Field(description="Why.")]
    source: Annotated[SourceName, Field(description="The source that failed.")]
