# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: SourceVisibility

from __future__ import annotations

from enum import StrEnum


class SourceVisibility(StrEnum):
    SourceVisibilityPublic = "public"
    SourceVisibilityPrivate = "private"
    SourceVisibilityUnknown = "unknown"
