# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: SourceRoute

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field, RootModel


class SourceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name a configuration document gives one configured source.",
            pattern="^[a-z0-9][a-z0-9-]*$",
        ),
    ]


class SourceRoute(BaseModel):
    destination: Annotated[
        SourceName,
        Field(description="The source the item lands in: the routed one, or the source itself."),
    ]
    route: Annotated[
        int | None,
        Field(
            description="The index of the route entry that matched, or `None` when none did and the item\nstays in the source itself.",
            ge=0,
        ),
    ] = None
    source: Annotated[SourceName, Field(description="The source the item would be written to.")]
