# ruff: noqa: E501
# generated by datamodel-codegen:
#   schema root: SourceFailure

from typing import Annotated, Literal

from pydantic import BaseModel, Field, RootModel


class SourceError1(BaseModel):
    kind: Literal["config"]
    message: Annotated[str, Field(description="What is wrong, in a form a user can act on.")]


class SourceError2(BaseModel):
    kind: Literal["auth"]
    message: Annotated[str, Field(description="What failed. Never contains the credential itself.")]


class SourceError3(BaseModel):
    kind: Literal["refused"]
    message: Annotated[str, Field(description="The source's own reason.")]


class SourceError4(BaseModel):
    kind: Literal["rate-limited"]
    retry_after_seconds: Annotated[
        int | None,
        Field(description="How long the source asked us to wait, when it said.", ge=0),
    ] = None


class SourceError5(BaseModel):
    kind: Literal["unavailable"]
    message: Annotated[str, Field(description="What went wrong reaching it.")]


class SourceError6(BaseModel):
    kind: Literal["malformed"]
    message: Annotated[str, Field(description="What could not be represented.")]


class SourceError(
    RootModel[
        SourceError1 | SourceError2 | SourceError3 | SourceError4 | SourceError5 | SourceError6
    ]
):
    root: Annotated[
        SourceError1 | SourceError2 | SourceError3 | SourceError4 | SourceError5 | SourceError6,
        Field(
            description="Why a source could not answer.\n\nEvery variant carries owned data only, so an error survives the JSON-over-stdio\nboundary a subprocess-hosted plugin crosses without losing anything."
        ),
    ]


class SourceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name a configuration document gives one configured source.",
            pattern="^[a-z0-9][a-z0-9-]*$",
        ),
    ]


class SourceFailure(BaseModel):
    error: Annotated[SourceError, Field(description="Why.")]
    source: Annotated[SourceName, Field(description="The source that failed.")]
