# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: SourceListing

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, Field, RootModel


class DependencySupport(StrEnum):
    DependencySupportBothDirections = "both-directions"
    DependencySupportForwardOnly = "forward-only"


class SourceErrorConfig(BaseModel):
    kind: Literal["config"]
    message: Annotated[str, Field(description="What is wrong, in a form a user can act on.")]


class SourceErrorAuth(BaseModel):
    kind: Literal["auth"]
    message: Annotated[str, Field(description="What failed. Never contains the credential itself.")]


class SourceErrorRefused(BaseModel):
    kind: Literal["refused"]
    message: Annotated[str, Field(description="The source's own reason.")]


class SourceErrorRateLimited(BaseModel):
    kind: Literal["rate-limited"]
    retry_after_seconds: Annotated[
        int | None,
        Field(description="How long the source asked us to wait, when it said.", ge=0),
    ] = None


class SourceErrorUnavailable(BaseModel):
    kind: Literal["unavailable"]
    message: Annotated[str, Field(description="What went wrong reaching it.")]


class SourceErrorMalformed(BaseModel):
    kind: Literal["malformed"]
    message: Annotated[str, Field(description="What could not be represented.")]


class SourceError(
    RootModel[
        SourceErrorConfig
        | SourceErrorAuth
        | SourceErrorRefused
        | SourceErrorRateLimited
        | SourceErrorUnavailable
        | SourceErrorMalformed
    ]
):
    root: Annotated[
        SourceErrorConfig
        | SourceErrorAuth
        | SourceErrorRefused
        | SourceErrorRateLimited
        | SourceErrorUnavailable
        | SourceErrorMalformed,
        Field(
            description="Why a source could not answer.\n\nEvery variant carries owned data only, so an error survives the JSON-over-stdio\nboundary a subprocess-hosted plugin crosses without losing anything."
        ),
    ]


class SourceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name a configuration document gives one configured source.",
            pattern="^[a-z0-9][a-z0-9-]*$",
        ),
    ]


class Support(StrEnum):
    SupportNative = "native"
    SupportUnsupported = "unsupported"


class SourceListingUnavailable(BaseModel):
    kind: Annotated[
        str,
        Field(
            description="The plugin kind behind it.\n\nA `String` because the vocabulary is open, not because it was not thought about:\nthis is the kind a source reports, and a subprocess-hosted plugin reports one\narriving over the wire from a binary this workspace never compiled. No\ncompile-time enumeration can hold that, and a newtype over the same string would\nonly move where an unrelated value is accepted."
        ),
    ]
    source: Annotated[SourceName, Field(description="The name the configuration gave it.")]
    error: Annotated[SourceError, Field(description="Why not.")]
    state: Literal["unavailable"]


class Capabilities(BaseModel):
    documents: Annotated[
        Support | None,
        Field(
            description="Whether the source has documents at all.\n\nThe same shape as [`projects`](Self::projects), and read the same way: it says what\nthe source *holds*, not which predicate it applies. It is therefore **not** one of\nthe predicates the second capability rule reaches — there is no wider result set to\nreturn and nothing for the engine to narrow. A source declaring `Unsupported` is\nnever asked for a document at all; the engine reads this once at the handshake,\nexactly as it reads [`TaskSource::writes`](crate::TaskSource::writes), and a\ndocument read across several sources reports such a source as holding none rather\nthan as having failed.\n\nDefaulted to [`Support::Unsupported`] when a wire value omits it, so a plugin that\npredates documents says nothing here and is read as the document-free source it is."
        ),
    ] = Support.SupportUnsupported
    filter_by_label: Annotated[
        Support, Field(description="Whether the source filters by label itself.")
    ]
    filter_by_status: Annotated[
        Support, Field(description="Whether the source filters by status itself.")
    ]
    max_page_size: Annotated[
        int,
        Field(
            description="The largest page the source will serve. At least 1 — a source that serves no rows\ncannot be paged, and every implementation rejects zero where its config is read.",
            ge=1,
        ),
    ]
    orphan_tasks: Annotated[
        Support,
        Field(description="Whether the source can select tasks belonging to no project."),
    ]
    project_dependencies: Annotated[
        DependencySupport,
        Field(description="How far the source can walk project dependencies."),
    ]
    projects: Annotated[Support, Field(description="Whether the source has projects at all.")]
    search_content: Annotated[
        Support, Field(description="Whether the source searches bodies itself.")
    ]
    search_title: Annotated[
        Support, Field(description="Whether the source searches titles itself.")
    ]
    task_dependencies: Annotated[
        DependencySupport,
        Field(description="How far the source can walk task dependencies."),
    ]


class SourceListingAvailable(BaseModel):
    kind: Annotated[
        str,
        Field(
            description="The plugin kind behind it.\n\nA `String` because the vocabulary is open, not because it was not thought about:\nthis is the kind a source reports, and a subprocess-hosted plugin reports one\narriving over the wire from a binary this workspace never compiled. No\ncompile-time enumeration can hold that, and a newtype over the same string would\nonly move where an unrelated value is accepted."
        ),
    ]
    source: Annotated[SourceName, Field(description="The name the configuration gave it.")]
    capabilities: Annotated[Capabilities, Field(description="What it applies itself.")]
    state: Literal["available"]


class SourceListing(RootModel[SourceListingAvailable | SourceListingUnavailable]):
    root: Annotated[
        SourceListingAvailable | SourceListingUnavailable,
        Field(
            description="What one configured source is, as `sources list` reports it.",
            title="SourceListing",
        ),
    ]
