# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: SourceName

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel


class SourceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name a configuration document gives one configured source.",
            pattern="^[a-z0-9][a-z0-9-]*$",
            title="SourceName",
        ),
    ]
