# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: StatusCategory

from enum import StrEnum


class StatusCategory(StrEnum):
    StatusCategoryDraft = "draft"
    StatusCategoryBacklog = "backlog"
    StatusCategoryTodo = "todo"
    StatusCategoryInProgress = "in-progress"
    StatusCategoryDone = "done"
    StatusCategoryCancelled = "cancelled"
    StatusCategoryUnknown = "unknown"
