# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: StatusMapping

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class StatusCategory(StrEnum):
    StatusCategoryDraft = "draft"
    StatusCategoryBacklog = "backlog"
    StatusCategoryTodo = "todo"
    StatusCategoryQueued = "queued"
    StatusCategoryInProgress = "in-progress"
    StatusCategoryDone = "done"
    StatusCategoryCancelled = "cancelled"
    StatusCategoryUnknown = "unknown"


class StatusName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="One status name a source's backend holds, matched ignoring case. Never blank.",
            min_length=1,
            pattern="\\S",
        ),
    ]


class StatusNames1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    task: StatusName


class StatusNames2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    project: StatusName


class StatusNames3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    project: StatusName
    task: StatusName


class StatusNames(RootModel[StatusName | StatusNames1 | StatusNames2 | StatusNames3]):
    root: Annotated[
        StatusName | StatusNames1 | StatusNames2 | StatusNames3,
        Field(
            description="What one category of a status_mapping names: one name for every item kind, or an object naming it for a task, for a project, or for each. A kind the object leaves out leaves the category unmapped for that kind."
        ),
    ]


class StatusMapping(RootModel[dict[StatusCategory, StatusNames | None]]):
    root: Annotated[
        dict[StatusCategory, StatusNames | None],
        Field(
            description="Which name each status category is, for each item kind. Keyed by status category; each value is one name for every kind, null to disable the category for every kind, or an object naming it for a task, a project or each.",
            title="StatusMapping",
        ),
    ]
