# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: StatusNamesReport

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, Field, RootModel


class ItemKind(StrEnum):
    ItemKindTask = "task"
    ItemKindProject = "project"


class LinearTeam(RootModel[str]):
    root: Annotated[str, Field(description="A Linear team's key or id.", min_length=1)]


class SourceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name a configuration document gives one configured source.",
            pattern="^[a-z0-9][a-z0-9-]*$",
        ),
    ]


class StatusCategory(StrEnum):
    StatusCategoryDraft = "draft"
    StatusCategoryBacklog = "backlog"
    StatusCategoryTodo = "todo"
    StatusCategoryQueued = "queued"
    StatusCategoryInProgress = "in-progress"
    StatusCategoryDone = "done"
    StatusCategoryCancelled = "cancelled"
    StatusCategoryUnknown = "unknown"


class StatusName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="One status name a source's backend holds, matched ignoring case. Never blank.",
            min_length=1,
            pattern="\\S",
        ),
    ]


class MappedStatusName(BaseModel):
    category: Annotated[
        StatusCategory, Field(description="The category the mapping sends to the name.")
    ]
    created: Annotated[
        bool,
        Field(description="Whether this run created the name; absent when it did not."),
    ] = False
    expected_type: Annotated[
        str,
        Field(
            description="The type `--apply` creates a missing name of this category and kind as; a present name\nof another type is reported and left as it is."
        ),
    ]
    kind: Annotated[
        ItemKind,
        Field(
            description="`task` for a workflow state of the team, `project` for a project status of the workspace."
        ),
    ]
    name: Annotated[StatusName, Field(description="The name, as the mapping spells it.")]
    present: Annotated[
        bool,
        Field(
            description="Whether that kind's vocabulary has a name of that spelling, ignoring case."
        ),
    ]
    type: Annotated[
        str | None,
        Field(
            description="The name's type in Linear — a `WorkflowState.type` for a task, a `ProjectStatusType`\nfor a project — absent when it is missing."
        ),
    ] = None


class RefusedCreate(BaseModel):
    kind: Annotated[
        ItemKind,
        Field(
            description="Whether it was a workflow state (`task`) or a project status (`project`)."
        ),
    ]
    message: Annotated[str, Field(description="What Linear said.")]
    name: Annotated[StatusName, Field(description="The name it would have created.")]


class StatusNamesReport(BaseModel):
    names: Annotated[
        list[MappedStatusName],
        Field(
            description="Every name `status_mapping` gives a task, then every name it gives a project, each in\ncategory order. A bare name is reported once for each kind. Empty when it names none."
        ),
    ]
    refused: Annotated[
        RefusedCreate | None,
        Field(
            description="The create Linear refused, which stopped an `--apply`; absent when nothing was refused."
        ),
    ] = None
    source: Annotated[SourceName, Field(description="The configured source name.")]
    team: Annotated[LinearTeam, Field(description="The configured team, as `team` names it.")]
