# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: TaskUpdated

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, JsonValue, RootModel


class BudgetSpent(BaseModel):
    amount: Annotated[int, Field(description="How much was spent against it, in that unit.", ge=0)]
    budget: Annotated[
        str,
        Field(description="The budget, as the source names it — `graphql`, `rest`."),
    ]
    lower_bound: Annotated[
        bool,
        Field(
            description="Whether any part of `amount` was modelled by a source rather than reported by its\nbackend or counted, which makes `amount` a lower bound on what the backend charged\nrather than a measurement of it."
        ),
    ]
    unit: Annotated[str, Field(description="What it is metered in — `points`, `requests`.")]


class FailureClass(StrEnum):
    FailureClassRefused = "refused"
    FailureClassTransient = "transient"


class GlobalId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="One item, qualified by the source it came from.\n\nRendered `<source>:<native>` and parsed by splitting on the **first** colon,\nso a native id may contain colons freely."
        ),
    ]


class Location1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str


class Location2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str


class Location(RootModel[Location1 | Location2]):
    root: Annotated[
        Location1 | Location2,
        Field(
            description='Where an entity is, in the one form a consumer can act on without knowing the backend.\n\nExternally tagged with exactly two variants, so the JSON is `{"url": "https://…"}` or\n`{"path": "/home/…"}` and a consumer tells them apart by which key is present. A reader\nhanded one of these knows what to *do* with it — open a link, or print a path and read\nthe file out — which is what a bare string could not have said.\n\nIt carries no third case on purpose. `None` on the field is the third case, and it\nmeans the source did not say where the entity is, which is not the same as saying it is\nnowhere.\n\nThis does **not** redefine, replace or derive from the `url` field of [`Task`],\n[`Project`] or [`Document`]: a source that reports a web URL there goes on reporting\nit, and every existing consumer sees exactly what it saw.'
        ),
    ]


class NativeId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="A source's own opaque identifier for one item.\n\nDeliberately unvalidated: a native id is whatever the upstream system says it\nis, colons included. The engine parses a qualified id by splitting on the\n*first* colon precisely so this stays true."
        ),
    ]


class Priority(StrEnum):
    PriorityNone = "none"
    PriorityUrgent = "urgent"
    PriorityHigh = "high"
    PriorityMedium = "medium"
    PriorityLow = "low"


class Repository(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="A repository identified by its normalized origin, without a URL scheme or `.git` suffix."
        ),
    ]


class SourceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name a configuration document gives one configured source.",
            pattern="^[a-z0-9][a-z0-9-]*$",
        ),
    ]


class Spent(BaseModel):
    budgets: Annotated[
        list[BudgetSpent],
        Field(
            description="What those requests spent, one entry per budget and unit, ordered by budget name."
        ),
    ]
    requests: Annotated[
        int,
        Field(
            description="How many HTTP requests those sources sent for this command.",
            ge=0,
        ),
    ]


class StatusCategory(StrEnum):
    StatusCategoryDraft = "draft"
    StatusCategoryBacklog = "backlog"
    StatusCategoryTodo = "todo"
    StatusCategoryQueued = "queued"
    StatusCategoryInProgress = "in-progress"
    StatusCategoryDone = "done"
    StatusCategoryCancelled = "cancelled"
    StatusCategoryUnknown = "unknown"


class TaskRef(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="One task named by another task's [`Task::delivers`] or [`Task::delivered_by`].\n\nA string with one of two spellings, decided the way a [`DependencyEndpoint`] decides it:\none holding a colon is `<source>:<native>` and names a task of any source, and one\nwithout is a bare native id naming a task of the source that holds the list. So a\nnative id holding a colon cannot be named bare, exactly as it cannot in\n`onetaskgraph.depends_on`."
        ),
    ]


class UpdatedField(StrEnum):
    UpdatedFieldTitle = "title"
    UpdatedFieldContent = "content"
    UpdatedFieldStatus = "status"
    UpdatedFieldPriority = "priority"
    UpdatedFieldMetadata = "metadata"
    UpdatedFieldDelivers = "delivers"
    UpdatedFieldDependsOn = "depends-on"


class DeliveredWritten(BaseModel):
    deliverer: Annotated[
        GlobalId,
        Field(
            description="The deliverer whose write re-evaluated it — the one that just dropped it, when it was\nre-evaluated for being dropped."
        ),
    ]
    pruned: Annotated[
        list[GlobalId],
        Field(
            description="Deliverers its source read as not found, removed from its `delivered_by` on this\nwrite. Left out when there were none.",
            validate_default=True,
        ),
    ] = []
    ticket: Annotated[GlobalId, Field(description="The delivered task.")]
    from_: Annotated[StatusCategory, Field(alias="from", description="The category it read.")]
    outcome: Literal["written"]
    to: Annotated[StatusCategory, Field(description="The category written.")]


class DeliveredUnchanged(BaseModel):
    deliverer: Annotated[
        GlobalId,
        Field(
            description="The deliverer whose write re-evaluated it — the one that just dropped it, when it was\nre-evaluated for being dropped."
        ),
    ]
    pruned: Annotated[
        list[GlobalId],
        Field(
            description="Deliverers its source read as not found, removed from its `delivered_by` on this\nwrite. Left out when there were none.",
            validate_default=True,
        ),
    ] = []
    ticket: Annotated[GlobalId, Field(description="The delivered task.")]
    from_: Annotated[StatusCategory, Field(alias="from", description="The category it read.")]
    outcome: Literal["unchanged"]


class DeliveredLeft(BaseModel):
    deliverer: Annotated[
        GlobalId,
        Field(
            description="The deliverer whose write re-evaluated it — the one that just dropped it, when it was\nre-evaluated for being dropped."
        ),
    ]
    pruned: Annotated[
        list[GlobalId],
        Field(
            description="Deliverers its source read as not found, removed from its `delivered_by` on this\nwrite. Left out when there were none.",
            validate_default=True,
        ),
    ] = []
    ticket: Annotated[GlobalId, Field(description="The delivered task.")]
    from_: Annotated[StatusCategory, Field(alias="from", description="The category it read.")]
    outcome: Literal["left"]


class Failure(BaseModel):
    class_: Annotated[
        FailureClass,
        Field(
            alias="class",
            description="Whether repeating the request unchanged could change the answer.",
        ),
    ]
    kind: Annotated[
        str,
        Field(
            description="What failed: the causing source error's own `kind` when a source caused it, and\notherwise this product's kebab-case name for the failure, such as `no-such-item`."
        ),
    ]
    message: Annotated[
        str,
        Field(
            description="What the command reported on standard error, without its `onetaskgraph: ` prefix."
        ),
    ]
    retry_after_seconds: Annotated[
        int | None,
        Field(
            description="How many seconds a rate limit asked the caller to wait, or `null` when it named no\nwait.",
            ge=0,
        ),
    ]
    source: Annotated[
        SourceName | None,
        Field(description="The configured source the failure came from, or `null` when none did."),
    ]


class Label(BaseModel):
    color: Annotated[
        str | None,
        Field(description="The source's own colour for the label, when it has one."),
    ] = None
    id: Annotated[NativeId, Field(description="The source's own opaque identifier.")]
    name: Annotated[str, Field(description="What a user filtering across sources actually types.")]


class Status(BaseModel):
    category: Annotated[
        StatusCategory,
        Field(description="The normalised value filters compare against."),
    ]
    name: Annotated[str, Field(description="The source's own label for this status.")]


class Task(BaseModel):
    content: Annotated[
        str | None, Field(description="The long-form body, when the source has one.")
    ] = None
    created_at: Annotated[
        AwareDatetime | None,
        Field(description="When the source says the task was created."),
    ] = None
    delivered_by: Annotated[
        list[TaskRef],
        Field(
            description="Every task that delivers this one, by qualified id: the reverse of [`Self::delivers`].\n\n**Owned by the store, not by a source record and not by a copy.** The engine keeps it\nin step whenever it writes a task's `delivers`, through\n[`TaskSource::set_delivered_by`](crate::TaskSource::set_delivered_by); a source holds\nand reports it, and a copy keeps the destination's own rather than taking the\nsource's. Empty by default and left out of the wire when empty, as `delivers` is.",
            validate_default=True,
        ),
    ] = []
    delivers: Annotated[
        list[TaskRef],
        Field(
            description="The tasks this one delivers: finishing this task finishes them.\n\nEach entry is a [`TaskRef`] — `<source>:<native>` names a task of any source, and a\nbare native id names a task of the source holding this one — with no repeats and\nnever this task itself. Empty by default, and left out of the wire when empty, so a\nreader written before the field existed reads exactly what it read before.",
            validate_default=True,
        ),
    ] = []
    id: Annotated[NativeId, Field(description="The source's own opaque identifier.")]
    key: Annotated[
        str | None,
        Field(
            description="The short handle the backend shows people, beside [`id`](Self::id) and never\ninstead of it — a Linear issue's `ENG-123`, a GitHub issue's `1043`.\n\n**It is human-facing and it may change.** A Linear issue moved between teams gets a\nnew identifier and a GitHub issue transferred between repositories gets a new\nnumber, so nothing stores this in place of [`id`](Self::id) and nothing matches on\nit: `id` is what everything stores and matches on, and this is what a person says\nout loud.\n\nAbsent by default, so a source that predates this field — and every source with no\nseparate handle of its own — reads as `None`, which means *this backend has no\nshort handle for this task* rather than *the handle is the id*. A source never\ncopies [`id`](Self::id) here.\n\n**Read-only.** A source derives it on a read and never stores one it is handed: a\ntask arriving on an [`ItemWrite`](crate::ItemWrite) may still hold its source's key,\nand a destination ignores it."
        ),
    ] = None
    labels: Annotated[
        list[Label],
        Field(
            description="Inline rather than by id: a source returning a task already knows them."
        ),
    ]
    location: Annotated[
        Location | None,
        Field(
            description="Where this task is, when the source says (see [`Location`]).\n\nAbsent by default, so a source that predates this field — and every source that\nsimply does not say — reads as `None`, which means *the source did not say where\nthis is* rather than *this is nowhere*. It neither replaces nor derives from\n[`url`](Self::url), which goes on meaning exactly what it always did."
        ),
    ] = None
    metadata: Annotated[
        dict[str, JsonValue],
        Field(
            description="Caller-defined attributes, preserving their JSON types.\n\nKeys are free-form, with two reserved prefixes: `onetaskgraph.` belongs to this\nproduct — [`Repository::METADATA_KEY`] and [`DependencyEdge::RECORDED_KEY`] are\nthe two every source honours, and [`ItemKind::METADATA_KEY`] is one plugin's —\nand `onepipeline.` belongs to that consumer. Every other key is the caller's, and\na source returns it exactly as it holds it."
        ),
    ] = {}
    priority: Annotated[
        Priority,
        Field(
            description="The task's priority; `none` means none is set, and a source that cannot hold one\nreports `none`.\n\nDefaulted when a document omits it, so a task written before this field existed —\nand every task of a plugin that predates it — reads as [`Priority::None`]. Always\nwritten, so a reader never has to tell an absent member from a `none` one. Whether a\nsource can hold one at all is [`Capabilities::priority`](crate::Capabilities::priority),\nand the engine never hands a source declaring it cannot a priority other than `none`."
        ),
    ] = Priority.PriorityNone
    project: Annotated[
        NativeId | None,
        Field(description="`None` is a first-class case — an orphan task — not an edge case."),
    ] = None
    repositories: Annotated[
        list[Repository],
        Field(
            description="Normalized repository origins this task concerns, in source order and without\nrepeats.",
            validate_default=True,
        ),
    ] = []
    status: Annotated[Status, Field(description="The source's status, normalised and preserved.")]
    title: Annotated[str, Field(description="The one-line summary a user recognises the task by.")]
    updated_at: Annotated[
        AwareDatetime | None,
        Field(description="When the source says the task last changed."),
    ] = None
    url: Annotated[str | None, Field(description="Where a human can open this task.")] = None


class DeliveredFailed(BaseModel):
    deliverer: Annotated[
        GlobalId,
        Field(
            description="The deliverer whose write re-evaluated it — the one that just dropped it, when it was\nre-evaluated for being dropped."
        ),
    ]
    pruned: Annotated[
        list[GlobalId],
        Field(
            description="Deliverers its source read as not found, removed from its `delivered_by` on this\nwrite. Left out when there were none.",
            validate_default=True,
        ),
    ] = []
    ticket: Annotated[GlobalId, Field(description="The delivered task.")]
    failure: Annotated[
        Failure,
        Field(
            description="Why, as the failure object itself: the same `class`, `kind`, `source`, `message`\nand `retry_after_seconds` a failure document carries under its own `failure`\nmember — not that whole document nested again."
        ),
    ]
    from_: Annotated[
        StatusCategory | None,
        Field(alias="from", description="The category it read, when it could be read."),
    ] = None
    outcome: Literal["failed"]


class Delivered(RootModel[DeliveredWritten | DeliveredUnchanged | DeliveredLeft | DeliveredFailed]):
    root: Annotated[
        DeliveredWritten | DeliveredUnchanged | DeliveredLeft | DeliveredFailed,
        Field(description="What keeping one delivered task in step with one deliverer came to."),
    ]


class TaskUpdated(BaseModel):
    delivered: Annotated[
        list[Delivered],
        Field(
            description="As `set_task_status` reports it; re-evaluated whenever `status` or `delivers` was\nnamed, empty otherwise."
        ),
    ]
    id: Annotated[GlobalId, Field(description="The task updated.")]
    spent: Annotated[
        Spent | None,
        Field(
            description="What the source's meter says this call spent, as `CopyReport::spent` — and absent,\nnever zero, when the source does not meter its own requests."
        ),
    ] = None
    task: Annotated[
        Task,
        Field(
            description="The task as its source reads it back, with every entry of its `delivers` and\n`delivered_by` qualified."
        ),
    ]
    written: Annotated[
        list[UpdatedField],
        Field(description="The fields the source actually wrote — empty when nothing differed."),
    ]
