# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: TaskRef

from __future__ import annotations

from typing import Annotated

from pydantic import Field, RootModel


class TaskRef(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="One task named by another task's [`Task::delivers`] or [`Task::delivered_by`].\n\nA string with one of two spellings, decided the way a [`DependencyEndpoint`] decides it:\none holding a colon is `<source>:<native>` and names a task of any source, and one\nwithout is a bare native id naming a task of the source that holds the list. So a\nnative id holding a colon cannot be named bare, exactly as it cannot in\n`onetaskgraph.depends_on`.",
            title="TaskRef",
        ),
    ]
