# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: TaskPrioritySet

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, Field, RootModel


class GlobalId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="One item, qualified by the source it came from.\n\nRendered `<source>:<native>` and parsed by splitting on the **first** colon,\nso a native id may contain colons freely."
        ),
    ]


class Priority(StrEnum):
    PriorityNone = "none"
    PriorityUrgent = "urgent"
    PriorityHigh = "high"
    PriorityMedium = "medium"
    PriorityLow = "low"


class TaskPrioritySet(BaseModel):
    id: Annotated[GlobalId, Field(description="The task whose priority was set.")]
    priority: Annotated[
        Priority,
        Field(description="Its priority as its source reads it back after the write."),
    ]
