# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: TaskStatusSet

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, Field, RootModel


class FailureClass(StrEnum):
    FailureClassRefused = "refused"
    FailureClassTransient = "transient"


class GlobalId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="One item, qualified by the source it came from.\n\nRendered `<source>:<native>` and parsed by splitting on the **first** colon,\nso a native id may contain colons freely."
        ),
    ]


class SourceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name a configuration document gives one configured source.",
            pattern="^[a-z0-9][a-z0-9-]*$",
        ),
    ]


class StatusCategory(StrEnum):
    StatusCategoryDraft = "draft"
    StatusCategoryBacklog = "backlog"
    StatusCategoryTodo = "todo"
    StatusCategoryQueued = "queued"
    StatusCategoryInProgress = "in-progress"
    StatusCategoryDone = "done"
    StatusCategoryCancelled = "cancelled"
    StatusCategoryUnknown = "unknown"


class DeliveredWritten(BaseModel):
    deliverer: Annotated[
        GlobalId,
        Field(
            description="The deliverer whose write re-evaluated it — the one that just dropped it, when it was\nre-evaluated for being dropped."
        ),
    ]
    pruned: Annotated[
        list[GlobalId] | None,
        Field(
            description="Deliverers its source read as not found, removed from its `delivered_by` on this\nwrite. Left out when there were none.",
            validate_default=True,
        ),
    ] = []
    ticket: Annotated[GlobalId, Field(description="The delivered task.")]
    from_: Annotated[StatusCategory, Field(alias="from", description="The category it read.")]
    outcome: Literal["written"]
    to: Annotated[StatusCategory, Field(description="The category written.")]


class DeliveredUnchanged(BaseModel):
    deliverer: Annotated[
        GlobalId,
        Field(
            description="The deliverer whose write re-evaluated it — the one that just dropped it, when it was\nre-evaluated for being dropped."
        ),
    ]
    pruned: Annotated[
        list[GlobalId] | None,
        Field(
            description="Deliverers its source read as not found, removed from its `delivered_by` on this\nwrite. Left out when there were none.",
            validate_default=True,
        ),
    ] = []
    ticket: Annotated[GlobalId, Field(description="The delivered task.")]
    from_: Annotated[StatusCategory, Field(alias="from", description="The category it read.")]
    outcome: Literal["unchanged"]


class DeliveredLeft(BaseModel):
    deliverer: Annotated[
        GlobalId,
        Field(
            description="The deliverer whose write re-evaluated it — the one that just dropped it, when it was\nre-evaluated for being dropped."
        ),
    ]
    pruned: Annotated[
        list[GlobalId] | None,
        Field(
            description="Deliverers its source read as not found, removed from its `delivered_by` on this\nwrite. Left out when there were none.",
            validate_default=True,
        ),
    ] = []
    ticket: Annotated[GlobalId, Field(description="The delivered task.")]
    from_: Annotated[StatusCategory, Field(alias="from", description="The category it read.")]
    outcome: Literal["left"]


class Failure(BaseModel):
    class_: Annotated[
        FailureClass,
        Field(
            alias="class",
            description="Whether repeating the request unchanged could change the answer.",
        ),
    ]
    kind: Annotated[
        str,
        Field(
            description="What failed: the causing source error's own `kind` when a source caused it, and\notherwise this product's kebab-case name for the failure, such as `no-such-item`."
        ),
    ]
    message: Annotated[
        str,
        Field(
            description="What the command reported on standard error, without its `onetaskgraph: ` prefix."
        ),
    ]
    retry_after_seconds: Annotated[
        int | None,
        Field(
            description="How many seconds a rate limit asked the caller to wait, or `null` when it named no\nwait.",
            ge=0,
        ),
    ]
    source: Annotated[
        SourceName | None,
        Field(description="The configured source the failure came from, or `null` when none did."),
    ]


class Status(BaseModel):
    category: Annotated[
        StatusCategory,
        Field(description="The normalised value filters compare against."),
    ]
    name: Annotated[str, Field(description="The source's own label for this status.")]


class DeliveredFailed(BaseModel):
    deliverer: Annotated[
        GlobalId,
        Field(
            description="The deliverer whose write re-evaluated it — the one that just dropped it, when it was\nre-evaluated for being dropped."
        ),
    ]
    pruned: Annotated[
        list[GlobalId] | None,
        Field(
            description="Deliverers its source read as not found, removed from its `delivered_by` on this\nwrite. Left out when there were none.",
            validate_default=True,
        ),
    ] = []
    ticket: Annotated[GlobalId, Field(description="The delivered task.")]
    failure: Annotated[Failure, Field(description="Why, as every other verb reports a failure.")]
    from_: Annotated[
        StatusCategory | None,
        Field(alias="from", description="The category it read, when it could be read."),
    ] = None
    outcome: Literal["failed"]


class Delivered(RootModel[DeliveredWritten | DeliveredUnchanged | DeliveredLeft | DeliveredFailed]):
    root: Annotated[
        DeliveredWritten | DeliveredUnchanged | DeliveredLeft | DeliveredFailed,
        Field(description="What keeping one delivered task in step with one deliverer came to."),
    ]


class TaskStatusSet(BaseModel):
    delivered: Annotated[
        list[Delivered],
        Field(
            description="One entry per task it delivers, or dropped, that this write re-evaluated. Empty when\nit delivers nothing."
        ),
    ]
    id: Annotated[GlobalId, Field(description="The task whose status was set.")]
    status: Annotated[Status, Field(description="Its status as its source reads it back.")]
