# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: TemplateAnswers

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class TemplateAnswers(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
