# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: TemplateVariables

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, Field


class ItemType(StrEnum):
    ItemTypeString = "string"
    ItemTypeObject = "object"


class VariableType(StrEnum):
    VariableTypeString = "string"
    VariableTypeText = "text"
    VariableTypeInteger = "integer"
    VariableTypeBoolean = "boolean"
    VariableTypeList = "list"
    VariableTypeObject = "object"


class TemplateVariable(BaseModel):
    declared_in: Annotated[
        str,
        Field(
            description="The chain file whose declaration this is: the one nearest the rendered template."
        ),
    ]
    # A default is arbitrary JSON by the emitted wire contract: a value of the
    # variable's own `type`, which the declaration beside it names.
    default: Annotated[Any | None, Field(description="The value used when no answer is given.")] = (
        None
    )
    description: Annotated[str, Field(description="What the variable is for; what a prompt shows.")]
    items: Annotated[
        ItemType | None,
        Field(description="What each entry holds, for a `list` variable and no other."),
    ] = None
    name: Annotated[str, Field(description="The variable's name, as the template body uses it.")]
    required: Annotated[
        bool,
        Field(
            description="Whether rendering without an answer is refused. An optional variable with no answer\nand no default renders as `none`."
        ),
    ]
    type: Annotated[VariableType, Field(description="What the variable holds.")]


class TemplateVariables(BaseModel):
    digest: Annotated[
        str,
        Field(
            description="The chain's digest: `sha256:` and 64 lowercase hex digits, over every file it reads\nin first-load order — each template an expression names counted as it names one when\nevery variable takes its default."
        ),
    ]
    template: Annotated[str, Field(description="The rendered template's resolved name.")]
    variables: Annotated[
        list[TemplateVariable],
        Field(description="Every declared variable, in declaration order along the chain."),
    ]
