# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: TemplateProvenance

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class TemplateProvenance(BaseModel):
    answers_digest: Annotated[
        str,
        Field(
            description="`sha256:` and the lowercase hex SHA-256 of the resolved answers — defaults applied — as\ncanonical JSON: keys sorted, no insignificant whitespace, UTF-8."
        ),
    ]
    body_digest: Annotated[
        str,
        Field(
            description="`sha256:` and the lowercase hex SHA-256 of the item's content exactly as written."
        ),
    ]
    digest: Annotated[
        str,
        Field(
            description="The chain digest the content was rendered with: `sha256:` and 64 lowercase hex digits."
        ),
    ]
    template: Annotated[
        str,
        Field(
            description="The template it was rendered from: the absolute path of a template file, or a loader\ndocument's `reference` verbatim. Recorded whole, whatever its length."
        ),
    ]
