# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: TemplateProvenance

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Sha256Digest(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="`sha256:` and 64 lowercase hex digits.",
            pattern="^sha256:[0-9a-f]{64}$",
        ),
    ]


class TemplateProvenance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    answers_digest: Annotated[
        Sha256Digest,
        Field(
            description="The SHA-256 of the resolved answers — defaults applied — as canonical JSON: keys sorted,\nno insignificant whitespace, UTF-8."
        ),
    ]
    body_digest: Annotated[
        Sha256Digest,
        Field(description="The SHA-256 of the item's content exactly as written."),
    ]
    digest: Annotated[
        Sha256Digest,
        Field(description="The chain digest the content was rendered with."),
    ]
    template: Annotated[
        str,
        Field(
            description="The template it was rendered from: the absolute path of a template file, or a loader\ndocument's `reference` verbatim. Recorded whole, whatever its length."
        ),
    ]
