# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: UpdatedField

from __future__ import annotations

from enum import StrEnum


class UpdatedField(StrEnum):
    UpdatedFieldTitle = "title"
    UpdatedFieldContent = "content"
    UpdatedFieldStatus = "status"
    UpdatedFieldPriority = "priority"
    UpdatedFieldMetadata = "metadata"
    UpdatedFieldDelivers = "delivers"
    UpdatedFieldDependsOn = "depends-on"
