# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: VariableType

from __future__ import annotations

from enum import StrEnum


class VariableType(StrEnum):
    VariableTypeString = "string"
    VariableTypeText = "text"
    VariableTypeInteger = "integer"
    VariableTypeBoolean = "boolean"
    VariableTypeList = "list"
    VariableTypeObject = "object"
