# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: WorkflowStatesReport

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, Field, RootModel


class LinearTeam(RootModel[str]):
    root: Annotated[str, Field(description="A Linear team's key or id.", min_length=1)]


class LinearWorkflowStateName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name of one workflow state of a Linear team.\n\nValidated on the way in rather than checked later, so a blank name — which no workflow\nstate can have — is a state this type cannot hold.",
            min_length=1,
        ),
    ]


class SourceName(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="The name a configuration document gives one configured source.",
            pattern="^[a-z0-9][a-z0-9-]*$",
        ),
    ]


class StatusCategory(StrEnum):
    StatusCategoryDraft = "draft"
    StatusCategoryBacklog = "backlog"
    StatusCategoryTodo = "todo"
    StatusCategoryQueued = "queued"
    StatusCategoryInProgress = "in-progress"
    StatusCategoryDone = "done"
    StatusCategoryCancelled = "cancelled"
    StatusCategoryUnknown = "unknown"


class MappedWorkflowState(BaseModel):
    category: Annotated[
        StatusCategory,
        Field(description="The category the mapping sends to the state."),
    ]
    present: Annotated[
        bool,
        Field(description="Whether the configured team has a workflow state of that name."),
    ]
    state: Annotated[
        LinearWorkflowStateName,
        Field(description="The state's name, as the mapping spells it."),
    ]
    type: Annotated[
        str | None,
        Field(
            description="The state's `WorkflowState.type` on the team — `backlog`, `unstarted`, `started`,\n`completed`, `canceled`, `triage` or another Linear names — absent when it is missing."
        ),
    ] = None


class WorkflowStatesReport(BaseModel):
    source: Annotated[SourceName, Field(description="The configured source name.")]
    states: Annotated[
        list[MappedWorkflowState],
        Field(
            description="Every workflow state `status_mapping` names, in category order. Empty when the mapping\nnames none."
        ),
    ]
    team: Annotated[LinearTeam, Field(description="The configured team, as `team` names it.")]
