# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: WritePolicyConfig

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class PolicyCommand(RootModel[list[str]]):
    root: Annotated[
        list[str],
        Field(description="One command line: the program, then its arguments, never empty."),
    ]


class WritePolicyConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    check_command: Annotated[
        PolicyCommand | None,
        Field(
            description="The command that decides whether a write may reach a public destination."
        ),
    ] = None
    visibility_command: Annotated[
        PolicyCommand | None,
        Field(description="The command that answers a repository's visibility."),
    ] = None
