# ruff: noqa: E501  # Generated descriptions preserve the schema's text.
# generated by datamodel-codegen:
#   schema root: WriteVerdict

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field, RootModel


class WriteVerdictPass(BaseModel):
    verdict: Literal["pass"]


class WriteVerdictRefuse(BaseModel):
    reason: Annotated[str, Field(description="Where, in neutral words.")]
    verdict: Literal["refuse"]


class WriteVerdictUnavailable(BaseModel):
    reason: Annotated[str, Field(description="Why, in neutral words.")]
    verdict: Literal["unavailable"]


class WriteVerdict(RootModel[WriteVerdictPass | WriteVerdictRefuse | WriteVerdictUnavailable]):
    root: Annotated[
        WriteVerdictPass | WriteVerdictRefuse | WriteVerdictUnavailable,
        Field(
            description="What a check decided about one write.\n\nEvery reason is neutral — it says where the check stopped and never what it found — so a\nrefusal can be printed wherever the write was asked for.",
            title="WriteVerdict",
        ),
    ]
