import { spawnSync } from "node:child_process";
import { readFileSync, realpathSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { compile } from "json-schema-to-typescript";

type Bundle = {
  version: number;
  roots: Record<string, Record<string, unknown>>;
  commands: string[];
};

const argumentsGiven = process.argv.slice(2);
if (argumentsGiven.some((argument) => argument !== "--check")) {
  throw new Error("generate: unknown argument; next: use no argument or '--check'");
}

const packageRoot = resolve(import.meta.dir, "..");
const configuredGeneratedRoot = process.env.ONETASKGRAPH_GENERATED_DIR;
if (
  configuredGeneratedRoot !== undefined &&
  (process.env.NODE_ENV !== "test" ||
    !realpathSync(configuredGeneratedRoot).startsWith(`${realpathSync(tmpdir())}/`))
) {
  throw new Error(
    "generate: ONETASKGRAPH_GENERATED_DIR is only accepted under the test temporary " +
      "directory; next: remove it for normal generation",
  );
}
const generatedRoot = configuredGeneratedRoot ?? resolve(packageRoot, "src/generated");
const workspaceRoot = resolve(packageRoot, "../..");
const binary = process.env.ONETASKGRAPH_BIN ?? resolve(workspaceRoot, "target/debug/onetaskgraph");
const binaryEnvironment = { ...process.env };
delete binaryEnvironment.ONETASKGRAPH_BIN;
delete binaryEnvironment.ONETASKGRAPH_GENERATED_DIR;
const emitted = spawnSync(binary, ["schema"], {
  cwd: workspaceRoot,
  encoding: "utf8",
  env: binaryEnvironment,
});
if (emitted.status !== 0) {
  const failure = (emitted.error?.message ?? emitted.stderr.trim()) || `exit ${emitted.status}`;
  throw new Error(
    `could not emit the SDK contract with ${binary}: ${failure}; ` +
      "next: build the onetaskgraph binary or set ONETASKGRAPH_BIN",
  );
}
let candidate: unknown;
try {
  candidate = JSON.parse(emitted.stdout);
} catch (error) {
  throw new Error(
    `the binary emitted malformed JSON: ${String(error)}; next: run 'onetaskgraph schema'`,
  );
}
if (
  typeof candidate !== "object" ||
  candidate === null ||
  !("version" in candidate) ||
  typeof candidate.version !== "number" ||
  !Number.isInteger(candidate.version) ||
  !("roots" in candidate) ||
  typeof candidate.roots !== "object" ||
  candidate.roots === null ||
  Array.isArray(candidate.roots) ||
  Object.values(candidate.roots).some(
    (schema) =>
      typeof schema !== "object" ||
      schema === null ||
      !("$schema" in schema) ||
      typeof schema.$schema !== "string",
  ) ||
  !("commands" in candidate) ||
  !Array.isArray(candidate.commands) ||
  candidate.commands.some(
    (command) => typeof command !== "string" || !/^[a-z][a-z-]*( [a-z][a-z-]*)*$/.test(command),
  ) ||
  new Set(candidate.commands).size !== candidate.commands.length
) {
  throw new Error(
    "the binary emitted an invalid schema bundle; next: run 'onetaskgraph schema' and fix " +
      "the version, roots, or commands field named there",
  );
}
// Every field was narrowed above, including each schema and command element.
const bundle: Bundle = candidate;

const declarations: string[] = [
  "/* Generated by scripts/generate.ts. Do not edit. */",
  "// Literal version keeps generated consumers pinned to this exact contract.",
  `export const SCHEMA_BUNDLE_VERSION = ${bundle.version} as const;`,
];
for (const [name, schema] of Object.entries(bundle.roots)) {
  let generated: string;
  try {
    generated = await compile({ ...schema, title: name }, name, {
      bannerComment: "",
      format: false,
      unknownAny: false,
    });
  } catch (error) {
    throw new Error(
      `generate: root ${name} is not compilable JSON Schema: ${String(error)}; ` +
        "next: fix that emitted schema root",
    );
  }
  declarations.push(
    `export namespace Generated${name} {\n${generated}\n}\n` +
      `export type ${name} = Generated${name}.${name};`,
  );
}

const files = new Map<string, string>([
  ["models.ts", `${declarations.join("\n")}\n`],
  [
    "schemas.ts",
    `/* Generated by scripts/generate.ts. Do not edit. */\n` +
      `// Literal preservation lets validators select only emitted root names.\n` +
      `export const runtimeSchemas = ${JSON.stringify(bundle.roots, null, 2)} as const;\n`,
  ],
  [
    "commands.ts",
    `/* Generated by scripts/generate.ts. Do not edit. */\n` +
      `// Literal preservation makes command-surface drift a type-level value too.\n` +
      `export const binaryCommands = ${JSON.stringify(bundle.commands, null, 2)} as const;\n`,
  ],
]);

let stale = false;
for (const [relative, content] of files) {
  const path = resolve(generatedRoot, relative);
  if (argumentsGiven.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(path, "utf8");
    } catch {
      // A missing generated file is drift too.
    }
    if (current !== content) {
      console.error(`generate: src/generated/${relative} would change; run 'bun run generate'`);
      stale = true;
    }
  } else {
    try {
      writeFileSync(path, content);
    } catch (error) {
      throw new Error(
        `generate: could not write ${path}: ${String(error)}; next: check directory permissions`,
      );
    }
  }
}
if (stale) process.exit(1);
