import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { compile } from "json-schema-to-typescript";

type Bundle = {
  version: number;
  roots: Record<string, Record<string, unknown>>;
  commands: string[];
};

const packageRoot = resolve(import.meta.dir, "..");
const workspaceRoot = resolve(packageRoot, "../..");
const binary = process.env.ONETASKGRAPH_BIN ?? resolve(workspaceRoot, "target/debug/onetaskgraph");
const emitted = spawnSync(binary, ["schema"], { cwd: workspaceRoot, encoding: "utf8" });
if (emitted.status !== 0) {
  throw new Error(`could not emit the SDK contract with ${binary} (exit ${emitted.status})`);
}
const bundle = JSON.parse(emitted.stdout) as Bundle;
if (!Number.isInteger(bundle.version) || !bundle.roots || !Array.isArray(bundle.commands)) {
  throw new Error("the binary emitted an invalid schema bundle");
}

const declarations: string[] = [
  "/* Generated by scripts/generate.ts. Do not edit. */",
  `export const SCHEMA_BUNDLE_VERSION = ${bundle.version} as const;`,
];
for (const [name, schema] of Object.entries(bundle.roots)) {
  const generated = await compile({ ...schema, title: name }, name, {
    bannerComment: "",
    format: false,
    unknownAny: false,
  });
  declarations.push(
    `export namespace Generated${name} {\n${generated}\n}\n` +
      `export type ${name} = Generated${name}.${name};`,
  );
}

const files = new Map<string, string>([
  ["src/generated/models.ts", `${declarations.join("\n")}\n`],
  [
    "src/generated/schemas.ts",
    `/* Generated by scripts/generate.ts. Do not edit. */\n` +
      `export const runtimeSchemas = ${JSON.stringify(bundle.roots, null, 2)} as const;\n`,
  ],
  [
    "src/generated/commands.ts",
    `/* Generated by scripts/generate.ts. Do not edit. */\n` +
      `export const binaryCommands = ${JSON.stringify(bundle.commands, null, 2)} as const;\n`,
  ],
]);

let stale = false;
for (const [relative, content] of files) {
  const path = resolve(packageRoot, relative);
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(path, "utf8");
    } catch {
      // A missing generated file is drift too.
    }
    if (current !== content) {
      console.error(`generate: ${relative} would change; run 'bun run generate'`);
      stale = true;
    }
  } else {
    writeFileSync(path, content);
  }
}
if (stale) process.exit(1);
