import { spawnSync } from "node:child_process";
import { readFileSync, realpathSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { isAbsolute, relative, resolve } from "node:path";
import { compile } from "json-schema-to-typescript";

type Bundle = {
  version: number;
  roots: Record<string, Record<string, unknown>>;
  commands: string[];
};

const argumentsGiven = process.argv.slice(2);
if (argumentsGiven.some((argument) => argument !== "--check")) {
  throw new Error("generate: unknown argument; next: use no argument or '--check'");
}

const packageRoot = resolve(import.meta.dir, "..");
const configuredGeneratedRoot = process.env.ONETASKGRAPH_GENERATED_DIR;
if (configuredGeneratedRoot !== undefined) {
  let canonicalGeneratedRoot: string;
  try {
    canonicalGeneratedRoot = realpathSync(configuredGeneratedRoot);
  } catch (error) {
    throw new Error(
      `generate: could not resolve ONETASKGRAPH_GENERATED_DIR: ${String(error)}; ` +
        "next: create the directory or remove the override",
    );
  }
  const relativeToTemporaryDirectory = relative(realpathSync(tmpdir()), canonicalGeneratedRoot);
  if (
    process.env.NODE_ENV !== "test" ||
    relativeToTemporaryDirectory === "" ||
    relativeToTemporaryDirectory === ".." ||
    relativeToTemporaryDirectory.startsWith(`..${process.platform === "win32" ? "\\" : "/"}`) ||
    isAbsolute(relativeToTemporaryDirectory)
  ) {
    throw new Error(
      "generate: ONETASKGRAPH_GENERATED_DIR is only accepted under the test temporary " +
        "directory; next: remove it for normal generation",
    );
  }
}
const generatedRoot = configuredGeneratedRoot ?? resolve(packageRoot, "src/generated");
const workspaceRoot = resolve(packageRoot, "../..");
if (process.env.ONETASKGRAPH_BIN !== undefined && process.env.ONETASKGRAPH_BIN.trim() === "") {
  throw new Error(
    "generate: ONETASKGRAPH_BIN must be a non-empty executable path; next: remove it or set a path",
  );
}
const binary = process.env.ONETASKGRAPH_BIN ?? resolve(workspaceRoot, "target/debug/onetaskgraph");
const binaryEnvironment = { ...process.env };
delete binaryEnvironment.ONETASKGRAPH_BIN;
delete binaryEnvironment.ONETASKGRAPH_GENERATED_DIR;
const emitted = spawnSync(binary, ["schema"], {
  cwd: workspaceRoot,
  encoding: "utf8",
  env: binaryEnvironment,
});
if (emitted.status !== 0) {
  const failure =
    (emitted.error?.message ?? emitted.stderr.trim()) ||
    (emitted.signal === null ? `exit ${emitted.status}` : `signal ${emitted.signal}`);
  throw new Error(
    `could not emit the SDK contract with ${binary}: ${failure}; ` +
      "next: build the onetaskgraph binary or set ONETASKGRAPH_BIN",
  );
}
let candidate: unknown;
try {
  candidate = JSON.parse(emitted.stdout);
} catch (error) {
  throw new Error(
    `the binary emitted malformed JSON: ${String(error)}; next: run 'onetaskgraph schema'`,
  );
}
if (
  typeof candidate !== "object" ||
  candidate === null ||
  !("version" in candidate) ||
  typeof candidate.version !== "number" ||
  !Number.isInteger(candidate.version) ||
  candidate.version < 0 ||
  candidate.version > 4_294_967_295 ||
  !("roots" in candidate) ||
  typeof candidate.roots !== "object" ||
  candidate.roots === null ||
  Array.isArray(candidate.roots) ||
  Object.keys(candidate.roots).some((name) => !/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)) ||
  Object.values(candidate.roots).some(
    (schema) =>
      typeof schema !== "object" ||
      schema === null ||
      !("$schema" in schema) ||
      typeof schema.$schema !== "string",
  ) ||
  !("commands" in candidate) ||
  !Array.isArray(candidate.commands) ||
  candidate.commands.some(
    (command) => typeof command !== "string" || !/^[a-z][a-z-]*( [a-z][a-z-]*)*$/.test(command),
  ) ||
  new Set(candidate.commands).size !== candidate.commands.length
) {
  throw new Error(
    "the binary emitted an invalid schema bundle; next: run 'onetaskgraph schema' and fix " +
      "the version, roots, or commands field named there",
  );
}
// Every field was narrowed above, including each schema and command element.
const bundle: Bundle = candidate;

const declarations: string[] = [
  "/* Generated by scripts/generate.ts. Do not edit. */",
  "// Literal version keeps generated consumers pinned to this exact contract.",
  `export const SCHEMA_BUNDLE_VERSION = ${bundle.version} as const;`,
];
for (const [name, schema] of Object.entries(bundle.roots)) {
  let generated: string;
  try {
    generated = await compile({ ...schema, title: name }, name, {
      bannerComment: "",
      format: false,
      unknownAny: false,
    });
  } catch (error) {
    throw new Error(
      `generate: root ${name} is not compilable JSON Schema: ${String(error)}; ` +
        "next: fix that emitted schema root",
    );
  }
  declarations.push(
    `export namespace Generated${name} {\n${generated}\n}\n` +
      `export type ${name} = Generated${name}.${name};`,
  );
}

/// Generated output as this repository commits it: no line ends in whitespace.
///
/// `json-schema-to-typescript` renders a multi-paragraph schema `description` into a JSDoc
/// block by prefixing every line with `" * "`, so a paragraph break becomes a line that is
/// exactly `" * "` — trailing whitespace, which `git diff --check` reports against every
/// commit that adds a field documented in more than one paragraph. Rewording the Rust doc
/// comment to dodge that would leave the trap armed for the next field.
///
/// The Python generator has never had the problem because it hands its output to `ruff
/// format`, which strips this. `compile` is called with `format: false` here — prettier
/// would reflow the declarations this file then wraps in namespaces — so the one thing
/// that formatter was doing for us is done here instead.
function trimmed(source: string): string {
  return source
    .split("\n")
    .map((line) => line.replace(/[ \t]+$/, ""))
    .join("\n");
}

const emittedFiles = new Map<string, string>([
  ["models.ts", `${declarations.join("\n")}\n`],
  [
    "schemas.ts",
    `/* Generated by scripts/generate.ts. Do not edit. */\n` +
      `// Literal preservation lets validators select only emitted root names.\n` +
      `export const runtimeSchemas = ${JSON.stringify(bundle.roots, null, 2)} as const;\n`,
  ],
  [
    "commands.ts",
    `/* Generated by scripts/generate.ts. Do not edit. */\n` +
      `// Literal preservation makes command-surface drift a type-level value too.\n` +
      `export const binaryCommands = ${JSON.stringify(bundle.commands, null, 2)} as const;\n`,
  ],
]);
// Every file, rather than only the one that has the problem today: the rule is about what
// this repository commits, not about which renderer happens to break it.
const files = new Map([...emittedFiles].map(([name, content]) => [name, trimmed(content)]));

let stale = false;
for (const [relative, content] of files) {
  const path = resolve(generatedRoot, relative);
  if (argumentsGiven.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(path, "utf8");
    } catch {
      // A missing generated file is drift too.
    }
    if (current !== content) {
      console.error(`generate: src/generated/${relative} would change; run 'bun run generate'`);
      stale = true;
    }
  } else {
    try {
      writeFileSync(path, content);
    } catch (error) {
      throw new Error(
        `generate: could not write ${path}: ${String(error)}; next: check directory permissions`,
      );
    }
  }
}
if (stale) process.exit(1);
